# *************************************************************************
# Auto-generated IP creation script for system_management_wiz
# Source IP : xilinx.com:ip:system_management_wiz:1.3
# Generated : 2026-04-09 09:06:42
# *************************************************************************

create_ip -name system_management_wiz \
          -vendor xilinx.com \
          -library ip \
          -version 1.3 \
          -module_name system_management_wiz

set_ip_properties_safe system_management_wiz [list \
  CONFIG.ACQUISITION_TIME                                      {4} \
  CONFIG.ACQUISITION_TIME_VAUXP0_VAUXN0                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP10_VAUXN10                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP11_VAUXN11                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP12_VAUXN12                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP13_VAUXN13                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP14_VAUXN14                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP15_VAUXN15                      {false} \
  CONFIG.ACQUISITION_TIME_VAUXP1_VAUXN1                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP2_VAUXN2                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP3_VAUXN3                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP4_VAUXN4                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP5_VAUXN5                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP6_VAUXN6                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP7_VAUXN7                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP8_VAUXN8                        {false} \
  CONFIG.ACQUISITION_TIME_VAUXP9_VAUXN9                        {false} \
  CONFIG.ACQUISITION_TIME_VP_VN                                {false} \
  CONFIG.ADC_CONVERSION_RATE                                   {200} \
  CONFIG.ADC_OFFSET_AND_GAIN_CALIBRATION                       {false} \
  CONFIG.ADC_OFFSET_CALIBRATION                                {true} \
  CONFIG.ADVANCED_SIMULATIONS                                  {false} \
  CONFIG.ANALOG_BANK_SELECTION                                 {64} \
  CONFIG.AVERAGE_ENABLE_TEMPERATURE                            {true} \
  CONFIG.AVERAGE_ENABLE_TEMPERATURE_SLAVE0_SSIT                {true} \
  CONFIG.AVERAGE_ENABLE_TEMPERATURE_SLAVE1_SSIT                {true} \
  CONFIG.AVERAGE_ENABLE_TEMPERATURE_SLAVE2_SSIT                {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP0_VAUXN0                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP10_VAUXN10                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP11_VAUXN11                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP12_VAUXN12                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP13_VAUXN13                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP14_VAUXN14                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP15_VAUXN15                        {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP1_VAUXN1                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP2_VAUXN2                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP3_VAUXN3                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP4_VAUXN4                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP5_VAUXN5                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP6_VAUXN6                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP7_VAUXN7                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP8_VAUXN8                          {false} \
  CONFIG.AVERAGE_ENABLE_VAUXP9_VAUXN9                          {false} \
  CONFIG.AVERAGE_ENABLE_VBRAM                                  {true} \
  CONFIG.AVERAGE_ENABLE_VCCAUX                                 {true} \
  CONFIG.AVERAGE_ENABLE_VCCDDRO                                {false} \
  CONFIG.AVERAGE_ENABLE_VCCINT                                 {true} \
  CONFIG.AVERAGE_ENABLE_VCCPAUX                                {false} \
  CONFIG.AVERAGE_ENABLE_VCCPINT                                {false} \
  CONFIG.AVERAGE_ENABLE_VCCPSAUX                               {false} \
  CONFIG.AVERAGE_ENABLE_VCCPSINTFP                             {false} \
  CONFIG.AVERAGE_ENABLE_VCCPSINTLP                             {false} \
  CONFIG.AVERAGE_ENABLE_VP_VN                                  {false} \
  CONFIG.AVERAGE_ENABLE_VUSER0                                 {false} \
  CONFIG.AVERAGE_ENABLE_VUSER0_SLAVE0_SSIT                     {true} \
  CONFIG.AVERAGE_ENABLE_VUSER0_SLAVE1_SSIT                     {true} \
  CONFIG.AVERAGE_ENABLE_VUSER0_SLAVE2_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER1                                 {false} \
  CONFIG.AVERAGE_ENABLE_VUSER1_SLAVE0_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER1_SLAVE1_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER1_SLAVE2_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER2                                 {false} \
  CONFIG.AVERAGE_ENABLE_VUSER2_SLAVE0_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER2_SLAVE1_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER2_SLAVE2_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER3                                 {false} \
  CONFIG.AVERAGE_ENABLE_VUSER3_SLAVE0_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER3_SLAVE1_SSIT                     {false} \
  CONFIG.AVERAGE_ENABLE_VUSER3_SLAVE2_SSIT                     {false} \
  CONFIG.BIPOLAR_OPERATION                                     {false} \
  CONFIG.BIPOLAR_VAUXP0_VAUXN0                                 {false} \
  CONFIG.BIPOLAR_VAUXP10_VAUXN10                               {false} \
  CONFIG.BIPOLAR_VAUXP11_VAUXN11                               {false} \
  CONFIG.BIPOLAR_VAUXP12_VAUXN12                               {false} \
  CONFIG.BIPOLAR_VAUXP13_VAUXN13                               {false} \
  CONFIG.BIPOLAR_VAUXP14_VAUXN14                               {false} \
  CONFIG.BIPOLAR_VAUXP15_VAUXN15                               {false} \
  CONFIG.BIPOLAR_VAUXP1_VAUXN1                                 {false} \
  CONFIG.BIPOLAR_VAUXP2_VAUXN2                                 {false} \
  CONFIG.BIPOLAR_VAUXP3_VAUXN3                                 {false} \
  CONFIG.BIPOLAR_VAUXP4_VAUXN4                                 {false} \
  CONFIG.BIPOLAR_VAUXP5_VAUXN5                                 {false} \
  CONFIG.BIPOLAR_VAUXP6_VAUXN6                                 {false} \
  CONFIG.BIPOLAR_VAUXP7_VAUXN7                                 {false} \
  CONFIG.BIPOLAR_VAUXP8_VAUXN8                                 {false} \
  CONFIG.BIPOLAR_VAUXP9_VAUXN9                                 {false} \
  CONFIG.BIPOLAR_VP_VN                                         {false} \
  CONFIG.CHANNEL_AVERAGING                                     {None} \
  CONFIG.CHANNEL_ENABLE_CALIBRATION                            {true} \
  CONFIG.CHANNEL_ENABLE_TEMPERATURE                            {true} \
  CONFIG.CHANNEL_ENABLE_TEMPERATURE_SLAVE0_SSIT                {true} \
  CONFIG.CHANNEL_ENABLE_TEMPERATURE_SLAVE1_SSIT                {true} \
  CONFIG.CHANNEL_ENABLE_TEMPERATURE_SLAVE2_SSIT                {true} \
  CONFIG.CHANNEL_ENABLE_VAUXP0_VAUXN0                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP10_VAUXN10                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP11_VAUXN11                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP12_VAUXN12                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP13_VAUXN13                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP14_VAUXN14                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP15_VAUXN15                        {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP1_VAUXN1                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP2_VAUXN2                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP3_VAUXN3                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP4_VAUXN4                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP5_VAUXN5                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP6_VAUXN6                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP7_VAUXN7                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP8_VAUXN8                          {false} \
  CONFIG.CHANNEL_ENABLE_VAUXP9_VAUXN9                          {false} \
  CONFIG.CHANNEL_ENABLE_VBRAM                                  {true} \
  CONFIG.CHANNEL_ENABLE_VCCAUX                                 {true} \
  CONFIG.CHANNEL_ENABLE_VCCDDRO                                {false} \
  CONFIG.CHANNEL_ENABLE_VCCINT                                 {true} \
  CONFIG.CHANNEL_ENABLE_VCCPAUX                                {false} \
  CONFIG.CHANNEL_ENABLE_VCCPINT                                {false} \
  CONFIG.CHANNEL_ENABLE_VCCPSAUX                               {false} \
  CONFIG.CHANNEL_ENABLE_VCCPSINTFP                             {false} \
  CONFIG.CHANNEL_ENABLE_VCCPSINTLP                             {false} \
  CONFIG.CHANNEL_ENABLE_VP_VN                                  {true} \
  CONFIG.CHANNEL_ENABLE_VREFN                                  {false} \
  CONFIG.CHANNEL_ENABLE_VREFP                                  {false} \
  CONFIG.CHANNEL_ENABLE_VUSER0                                 {false} \
  CONFIG.CHANNEL_ENABLE_VUSER0_SLAVE0_SSIT                     {true} \
  CONFIG.CHANNEL_ENABLE_VUSER0_SLAVE1_SSIT                     {true} \
  CONFIG.CHANNEL_ENABLE_VUSER0_SLAVE2_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER1                                 {false} \
  CONFIG.CHANNEL_ENABLE_VUSER1_SLAVE0_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER1_SLAVE1_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER1_SLAVE2_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER2                                 {false} \
  CONFIG.CHANNEL_ENABLE_VUSER2_SLAVE0_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER2_SLAVE1_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER2_SLAVE2_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER3                                 {false} \
  CONFIG.CHANNEL_ENABLE_VUSER3_SLAVE0_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER3_SLAVE1_SSIT                     {false} \
  CONFIG.CHANNEL_ENABLE_VUSER3_SLAVE2_SSIT                     {false} \
  CONFIG.COMMON_N_SOURCE                                       {Vaux0} \
  CONFIG.COMMON_N_VAUXP0_VAUXN0                                {false} \
  CONFIG.COMMON_N_VAUXP10_VAUXN10                              {false} \
  CONFIG.COMMON_N_VAUXP11_VAUXN11                              {false} \
  CONFIG.COMMON_N_VAUXP12_VAUXN12                              {false} \
  CONFIG.COMMON_N_VAUXP13_VAUXN13                              {false} \
  CONFIG.COMMON_N_VAUXP14_VAUXN14                              {false} \
  CONFIG.COMMON_N_VAUXP15_VAUXN15                              {false} \
  CONFIG.COMMON_N_VAUXP1_VAUXN1                                {false} \
  CONFIG.COMMON_N_VAUXP2_VAUXN2                                {false} \
  CONFIG.COMMON_N_VAUXP3_VAUXN3                                {false} \
  CONFIG.COMMON_N_VAUXP4_VAUXN4                                {false} \
  CONFIG.COMMON_N_VAUXP5_VAUXN5                                {false} \
  CONFIG.COMMON_N_VAUXP6_VAUXN6                                {false} \
  CONFIG.COMMON_N_VAUXP7_VAUXN7                                {false} \
  CONFIG.COMMON_N_VAUXP8_VAUXN8                                {false} \
  CONFIG.COMMON_N_VAUXP9_VAUXN9                                {false} \
  CONFIG.Component_Name                                        {system_management_wiz} \
  CONFIG.DCLK_FREQUENCY                                        {100.0} \
  CONFIG.DUAL_SEQ_CALIBRATION                                  {false} \
  CONFIG.DUAL_SEQ_TEMPERATURE                                  {false} \
  CONFIG.DUAL_SEQ_TEMPERATURE_SLAVE0_SSIT                      {false} \
  CONFIG.DUAL_SEQ_TEMPERATURE_SLAVE1_SSIT                      {false} \
  CONFIG.DUAL_SEQ_TEMPERATURE_SLAVE2_SSIT                      {false} \
  CONFIG.DUAL_SEQ_VAUXP0_VAUXN0                                {false} \
  CONFIG.DUAL_SEQ_VAUXP10_VAUXN10                              {false} \
  CONFIG.DUAL_SEQ_VAUXP11_VAUXN11                              {false} \
  CONFIG.DUAL_SEQ_VAUXP12_VAUXN12                              {false} \
  CONFIG.DUAL_SEQ_VAUXP13_VAUXN13                              {false} \
  CONFIG.DUAL_SEQ_VAUXP14_VAUXN14                              {false} \
  CONFIG.DUAL_SEQ_VAUXP15_VAUXN15                              {false} \
  CONFIG.DUAL_SEQ_VAUXP1_VAUXN1                                {false} \
  CONFIG.DUAL_SEQ_VAUXP2_VAUXN2                                {false} \
  CONFIG.DUAL_SEQ_VAUXP3_VAUXN3                                {false} \
  CONFIG.DUAL_SEQ_VAUXP4_VAUXN4                                {false} \
  CONFIG.DUAL_SEQ_VAUXP5_VAUXN5                                {false} \
  CONFIG.DUAL_SEQ_VAUXP6_VAUXN6                                {false} \
  CONFIG.DUAL_SEQ_VAUXP7_VAUXN7                                {false} \
  CONFIG.DUAL_SEQ_VAUXP8_VAUXN8                                {false} \
  CONFIG.DUAL_SEQ_VAUXP9_VAUXN9                                {false} \
  CONFIG.DUAL_SEQ_VBRAM                                        {false} \
  CONFIG.DUAL_SEQ_VCCAUX                                       {false} \
  CONFIG.DUAL_SEQ_VCCDDRO                                      {false} \
  CONFIG.DUAL_SEQ_VCCINT                                       {false} \
  CONFIG.DUAL_SEQ_VCCPAUX                                      {false} \
  CONFIG.DUAL_SEQ_VCCPINT                                      {false} \
  CONFIG.DUAL_SEQ_VCCPSAUX                                     {false} \
  CONFIG.DUAL_SEQ_VCCPSINTFP                                   {false} \
  CONFIG.DUAL_SEQ_VCCPSINTLP                                   {false} \
  CONFIG.DUAL_SEQ_VP_VN                                        {false} \
  CONFIG.DUAL_SEQ_VREFN                                        {false} \
  CONFIG.DUAL_SEQ_VREFP                                        {false} \
  CONFIG.DUAL_SEQ_VUSER0                                       {false} \
  CONFIG.DUAL_SEQ_VUSER0_SLAVE0_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER0_SLAVE1_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER0_SLAVE2_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER1                                       {false} \
  CONFIG.DUAL_SEQ_VUSER1_SLAVE0_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER1_SLAVE1_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER1_SLAVE2_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER2                                       {false} \
  CONFIG.DUAL_SEQ_VUSER2_SLAVE0_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER2_SLAVE1_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER2_SLAVE2_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER3                                       {false} \
  CONFIG.DUAL_SEQ_VUSER3_SLAVE0_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER3_SLAVE1_SSIT                           {false} \
  CONFIG.DUAL_SEQ_VUSER3_SLAVE2_SSIT                           {false} \
  CONFIG.ENABLE_ADC_DATA_OUT_MASTER                            {false} \
  CONFIG.ENABLE_ADC_DATA_OUT_SLAVE0                            {false} \
  CONFIG.ENABLE_ADC_DATA_OUT_SLAVE1                            {false} \
  CONFIG.ENABLE_ADC_DATA_OUT_SLAVE2                            {false} \
  CONFIG.ENABLE_AXI4STREAM                                     {false} \
  CONFIG.ENABLE_BUSY                                           {true} \
  CONFIG.ENABLE_CALIBRATION_AVERAGING                          {true} \
  CONFIG.ENABLE_CHANNEL                                        {true} \
  CONFIG.ENABLE_CONVST                                         {false} \
  CONFIG.ENABLE_CONVSTCLK                                      {false} \
  CONFIG.ENABLE_DCLK                                           {true} \
  CONFIG.ENABLE_DNA                                            {true} \
  CONFIG.ENABLE_DRP                                            {true} \
  CONFIG.ENABLE_DUAL_SEQUENCE_MODE                             {false} \
  CONFIG.ENABLE_EOC                                            {true} \
  CONFIG.ENABLE_EOS                                            {true} \
  CONFIG.ENABLE_EXTERNAL_MUX                                   {false} \
  CONFIG.ENABLE_I2C                                            {false} \
  CONFIG.ENABLE_I2C_SLAVE                                      {false} \
  CONFIG.ENABLE_JTAGBUSY                                       {true} \
  CONFIG.ENABLE_JTAGLOCKED                                     {true} \
  CONFIG.ENABLE_JTAGMODIFIED                                   {true} \
  CONFIG.ENABLE_JTAG_ARBITER                                   {false} \
  CONFIG.ENABLE_PMBUS                                          {false} \
  CONFIG.ENABLE_RESET                                          {false} \
  CONFIG.ENABLE_TEMP_BUS                                       {false} \
  CONFIG.ENABLE_VBRAM_ALARM                                    {false} \
  CONFIG.ENABLE_VCCDDRO_ALARM                                  {false} \
  CONFIG.ENABLE_VCCPAUX_ALARM                                  {false} \
  CONFIG.ENABLE_VCCPINT_ALARM                                  {false} \
  CONFIG.ENABLE_VCCPSAUX_ALARM                                 {false} \
  CONFIG.ENABLE_VCCPSINTFP_ALARM                               {false} \
  CONFIG.ENABLE_VCCPSINTLP_ALARM                               {false} \
  CONFIG.EOS_GEN_RATE                                          {High_Rate} \
  CONFIG.EXTERNAL_MUXADDR_ENABLE                               {false} \
  CONFIG.EXTERNAL_MUX_CHANNEL                                  {VP_VN} \
  CONFIG.Enable_PMC                                            {false} \
  CONFIG.Enable_Slave0                                         {true} \
  CONFIG.Enable_Slave1                                         {false} \
  CONFIG.Enable_Slave2                                         {false} \
  CONFIG.FIFO_DEPTH                                            {7} \
  CONFIG.I2C_ADDRESS_OVERRIDE                                  {false} \
  CONFIG.I2C_CLK_FREQ                                          {0_4} \
  CONFIG.I2C_SCLK_LOC                                          {AY26} \
  CONFIG.I2C_SDA_LOC                                           {AY27} \
  CONFIG.I2C_SLAVE0_ADDRESS                                    {01} \
  CONFIG.I2C_SLAVE1_ADDRESS                                    {02} \
  CONFIG.I2C_SLAVE2_ADDRESS                                    {03} \
  CONFIG.I2C_SLAVE_ADDRESS                                     {00} \
  CONFIG.INCREASE_ACQUISITION_TIME                             {false} \
  CONFIG.INTERFACE_SELECTION                                   {Enable_AXI} \
  CONFIG.NUM_WAVE                                              {1} \
  CONFIG.NUM_WAVE_TEMP                                         {1} \
  CONFIG.NUM_WAVE_VAUXP0                                       {1} \
  CONFIG.NUM_WAVE_VAUXP1                                       {1} \
  CONFIG.NUM_WAVE_VAUXP10                                      {1} \
  CONFIG.NUM_WAVE_VAUXP11                                      {1} \
  CONFIG.NUM_WAVE_VAUXP12                                      {1} \
  CONFIG.NUM_WAVE_VAUXP13                                      {1} \
  CONFIG.NUM_WAVE_VAUXP14                                      {1} \
  CONFIG.NUM_WAVE_VAUXP15                                      {1} \
  CONFIG.NUM_WAVE_VAUXP2                                       {1} \
  CONFIG.NUM_WAVE_VAUXP3                                       {1} \
  CONFIG.NUM_WAVE_VAUXP4                                       {1} \
  CONFIG.NUM_WAVE_VAUXP5                                       {1} \
  CONFIG.NUM_WAVE_VAUXP6                                       {1} \
  CONFIG.NUM_WAVE_VAUXP7                                       {1} \
  CONFIG.NUM_WAVE_VAUXP8                                       {1} \
  CONFIG.NUM_WAVE_VAUXP9                                       {1} \
  CONFIG.NUM_WAVE_VCCAUX                                       {1} \
  CONFIG.NUM_WAVE_VCCINT                                       {1} \
  CONFIG.NUM_WAVE_VCCPSAUX                                     {1} \
  CONFIG.NUM_WAVE_VCCPSINTFP                                   {1} \
  CONFIG.NUM_WAVE_VCCPSINTLP                                   {1} \
  CONFIG.NUM_WAVE_VP                                           {1} \
  CONFIG.NUM_WAVE_VUSER0                                       {1} \
  CONFIG.NUM_WAVE_VUSER1                                       {1} \
  CONFIG.NUM_WAVE_VUSER2                                       {1} \
  CONFIG.NUM_WAVE_VUSER3                                       {1} \
  CONFIG.OT_ALARM                                              {false} \
  CONFIG.PMC_Mode                                              {Slave} \
  CONFIG.REFERENCE                                             {Internal} \
  CONFIG.SECONDARY_SEQUENCER_RATE                              {1} \
  CONFIG.SELECT_USER_SUPPLY0                                   {VCCO} \
  CONFIG.SELECT_USER_SUPPLY0_LEVEL                             {1.8} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE0_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE0_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE1_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE1_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE2_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY0_SLAVE2_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY1                                   {VCCINT} \
  CONFIG.SELECT_USER_SUPPLY1_LEVEL                             {0.9} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE0_SSIT                       {VCCINT} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE0_SSIT_LEVEL                 {0.9} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE1_SSIT                       {VCCINT} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE1_SSIT_LEVEL                 {0.9} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE2_SSIT                       {VCCINT} \
  CONFIG.SELECT_USER_SUPPLY1_SLAVE2_SSIT_LEVEL                 {0.9} \
  CONFIG.SELECT_USER_SUPPLY2                                   {VCCAUX} \
  CONFIG.SELECT_USER_SUPPLY2_LEVEL                             {1.8} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE0_SSIT                       {VCCAUX} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE0_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE1_SSIT                       {VCCAUX} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE1_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE2_SSIT                       {VCCAUX} \
  CONFIG.SELECT_USER_SUPPLY2_SLAVE2_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY3                                   {VCCO} \
  CONFIG.SELECT_USER_SUPPLY3_LEVEL                             {1.8} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE0_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE0_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE1_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE1_SSIT_LEVEL                 {1.8} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE2_SSIT                       {VCCO} \
  CONFIG.SELECT_USER_SUPPLY3_SLAVE2_SSIT_LEVEL                 {1.8} \
  CONFIG.SENSOR_OFFSET_AND_GAIN_CALIBRATION                    {true} \
  CONFIG.SENSOR_OFFSET_CALIBRATION                             {false} \
  CONFIG.SEQUENCER_MODE                                        {Continuous} \
  CONFIG.SEQUENCE_MODE_VAUXP0_VAUXN0                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP10_VAUXN10                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP11_VAUXN11                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP12_VAUXN12                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP13_VAUXN13                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP14_VAUXN14                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP15_VAUXN15                         {false} \
  CONFIG.SEQUENCE_MODE_VAUXP1_VAUXN1                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP2_VAUXN2                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP3_VAUXN3                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP4_VAUXN4                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP5_VAUXN5                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP6_VAUXN6                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP7_VAUXN7                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP8_VAUXN8                           {false} \
  CONFIG.SEQUENCE_MODE_VAUXP9_VAUXN9                           {false} \
  CONFIG.SERIAL_INTERFACE                                      {None} \
  CONFIG.SIM_FILE_NAME                                         {design} \
  CONFIG.SIM_FILE_REL_PATH                                     {./} \
  CONFIG.SIM_FILE_SEL                                          {Default} \
  CONFIG.SINGLE_CHANNEL_ACQUISITION_TIME                       {false} \
  CONFIG.SINGLE_CHANNEL_ENABLE_EXTERNAL                        {true} \
  CONFIG.SINGLE_CHANNEL_ENABLE_SENSOR                          {true} \
  CONFIG.SINGLE_CHANNEL_ENABLE_SLAVE0_SSIT                     {true} \
  CONFIG.SINGLE_CHANNEL_ENABLE_SLAVE1_SSIT                     {true} \
  CONFIG.SINGLE_CHANNEL_ENABLE_SLAVE2_SSIT                     {true} \
  CONFIG.SINGLE_CHANNEL_ENABLE_VUSER                           {true} \
  CONFIG.SINGLE_CHANNEL_SELECTION                              {TEMPERATURE} \
  CONFIG.SINGLE_CHANNEL_SELECTION_EXTERNAL                     {None} \
  CONFIG.SINGLE_CHANNEL_SELECTION_SENSOR                       {TEMPERATURE} \
  CONFIG.SINGLE_CHANNEL_SELECTION_SLAVE0_SSIT                  {TEMPERATURE_SLAVE0} \
  CONFIG.SINGLE_CHANNEL_SELECTION_SLAVE1_SSIT                  {TEMPERATURE_SLAVE1} \
  CONFIG.SINGLE_CHANNEL_SELECTION_SLAVE2_SSIT                  {TEMPERATURE_SLAVE2} \
  CONFIG.SINGLE_CHANNEL_SELECTION_VUSER                        {None} \
  CONFIG.STIMULUS_FREQ                                         {0.1} \
  CONFIG.STIMULUS_FREQ_TEMP                                    {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP0                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP1                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP10                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP11                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP12                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP13                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP14                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP15                                 {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP2                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP3                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP4                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP5                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP6                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP7                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP8                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VAUXP9                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VCCAUX                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VCCINT                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VCCPSAUX                                {0.1} \
  CONFIG.STIMULUS_FREQ_VCCPSINTFP                              {0.1} \
  CONFIG.STIMULUS_FREQ_VCCPSINTLP                              {0.1} \
  CONFIG.STIMULUS_FREQ_VP                                      {0.1} \
  CONFIG.STIMULUS_FREQ_VUSER0                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VUSER1                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VUSER2                                  {0.1} \
  CONFIG.STIMULUS_FREQ_VUSER3                                  {0.1} \
  CONFIG.SYSMONE1_STARUP_SELECTION                             {channel_sequencer} \
  CONFIG.S_AXI_ACLK.INSERT_VIP                                 {0} \
  CONFIG.S_AXI_ADDR_WIDTH                                      {32} \
  CONFIG.S_AXI_DATA_WIDTH                                      {32} \
  CONFIG.S_AXI_LITE.INSERT_VIP                                 {0} \
  CONFIG.S_AXI_RESETN.INSERT_VIP                               {0} \
  CONFIG.TEMPERATURE_ALARM_OT_RESET                            {70.0} \
  CONFIG.TEMPERATURE_ALARM_OT_TRIGGER                          {125.0} \
  CONFIG.TEMPERATURE_ALARM_RESET                               {60.0} \
  CONFIG.TEMPERATURE_ALARM_TRIGGER                             {85.0} \
  CONFIG.TIMING_MODE                                           {Continuous} \
  CONFIG.UNDER_OT_ALARM                                        {false} \
  CONFIG.UNDER_TEMP_ALARM                                      {false} \
  CONFIG.USER_SUPPLY0_ALARM                                    {false} \
  CONFIG.USER_SUPPLY0_ALARM_LOWER                              {1.79} \
  CONFIG.USER_SUPPLY0_ALARM_UPPER                              {1.81} \
  CONFIG.USER_SUPPLY0_BANK                                     {44} \
  CONFIG.USER_SUPPLY0_SLAVE0_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY0_SLAVE0_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY0_SLAVE0_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY0_SLAVE0_SSIT_BANK                         {68} \
  CONFIG.USER_SUPPLY0_SLAVE1_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY0_SLAVE1_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY0_SLAVE1_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY0_SLAVE1_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY0_SLAVE2_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY0_SLAVE2_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY0_SLAVE2_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY0_SLAVE2_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY1_ALARM                                    {false} \
  CONFIG.USER_SUPPLY1_ALARM_LOWER                              {0.89} \
  CONFIG.USER_SUPPLY1_ALARM_UPPER                              {0.91} \
  CONFIG.USER_SUPPLY1_BANK                                     {44} \
  CONFIG.USER_SUPPLY1_SLAVE0_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY1_SLAVE0_SSIT_ALARM_LOWER                  {0.89} \
  CONFIG.USER_SUPPLY1_SLAVE0_SSIT_ALARM_UPPER                  {0.91} \
  CONFIG.USER_SUPPLY1_SLAVE0_SSIT_BANK                         {68} \
  CONFIG.USER_SUPPLY1_SLAVE1_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY1_SLAVE1_SSIT_ALARM_LOWER                  {0.89} \
  CONFIG.USER_SUPPLY1_SLAVE1_SSIT_ALARM_UPPER                  {0.91} \
  CONFIG.USER_SUPPLY1_SLAVE1_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY1_SLAVE2_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY1_SLAVE2_SSIT_ALARM_LOWER                  {0.89} \
  CONFIG.USER_SUPPLY1_SLAVE2_SSIT_ALARM_UPPER                  {0.91} \
  CONFIG.USER_SUPPLY1_SLAVE2_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY2_ALARM                                    {false} \
  CONFIG.USER_SUPPLY2_ALARM_LOWER                              {1.79} \
  CONFIG.USER_SUPPLY2_ALARM_UPPER                              {1.81} \
  CONFIG.USER_SUPPLY2_BANK                                     {44} \
  CONFIG.USER_SUPPLY2_SLAVE0_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY2_SLAVE0_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY2_SLAVE0_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY2_SLAVE0_SSIT_BANK                         {68} \
  CONFIG.USER_SUPPLY2_SLAVE1_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY2_SLAVE1_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY2_SLAVE1_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY2_SLAVE1_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY2_SLAVE2_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY2_SLAVE2_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY2_SLAVE2_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY2_SLAVE2_SSIT_BANK                         {44} \
  CONFIG.USER_SUPPLY3_ALARM                                    {false} \
  CONFIG.USER_SUPPLY3_ALARM_LOWER                              {1.79} \
  CONFIG.USER_SUPPLY3_ALARM_UPPER                              {1.81} \
  CONFIG.USER_SUPPLY3_BANK                                     {65} \
  CONFIG.USER_SUPPLY3_SLAVE0_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY3_SLAVE0_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY3_SLAVE0_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY3_SLAVE0_SSIT_BANK                         {68} \
  CONFIG.USER_SUPPLY3_SLAVE1_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY3_SLAVE1_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY3_SLAVE1_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY3_SLAVE1_SSIT_BANK                         {65} \
  CONFIG.USER_SUPPLY3_SLAVE2_SSIT_ALARM                        {false} \
  CONFIG.USER_SUPPLY3_SLAVE2_SSIT_ALARM_LOWER                  {1.79} \
  CONFIG.USER_SUPPLY3_SLAVE2_SSIT_ALARM_UPPER                  {1.81} \
  CONFIG.USER_SUPPLY3_SLAVE2_SSIT_BANK                         {65} \
  CONFIG.USER_TEMP_ALARM                                       {false} \
  CONFIG.USE_BOARD_FLOW                                        {false} \
  CONFIG.VAUX0_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX10_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX11_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX12_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX13_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX14_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX15_BOARD_INTERFACE                                {Custom} \
  CONFIG.VAUX1_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX2_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX3_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX4_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX5_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX6_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX7_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX8_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUX9_BOARD_INTERFACE                                 {Custom} \
  CONFIG.VAUXN0_LOC                                            {BA14} \
  CONFIG.VAUXN10_LOC                                           {AW18} \
  CONFIG.VAUXN11_LOC                                           {AY20} \
  CONFIG.VAUXN12_LOC                                           {BB21} \
  CONFIG.VAUXN13_LOC                                           {BE20} \
  CONFIG.VAUXN14_LOC                                           {BE15} \
  CONFIG.VAUXN15_LOC                                           {BE16} \
  CONFIG.VAUXN1_LOC                                            {BB16} \
  CONFIG.VAUXN2_LOC                                            {AY17} \
  CONFIG.VAUXN3_LOC                                            {AW20} \
  CONFIG.VAUXN4_LOC                                            {BC20} \
  CONFIG.VAUXN5_LOC                                            {BD19} \
  CONFIG.VAUXN6_LOC                                            {BC16} \
  CONFIG.VAUXN7_LOC                                            {BD17} \
  CONFIG.VAUXN8_LOC                                            {AY15} \
  CONFIG.VAUXN9_LOC                                            {BC15} \
  CONFIG.VAUXP0_LOC                                            {AY14} \
  CONFIG.VAUXP10_LOC                                           {AW19} \
  CONFIG.VAUXP11_LOC                                           {AY21} \
  CONFIG.VAUXP12_LOC                                           {BA21} \
  CONFIG.VAUXP13_LOC                                           {BE21} \
  CONFIG.VAUXP14_LOC                                           {BD15} \
  CONFIG.VAUXP15_LOC                                           {BE17} \
  CONFIG.VAUXP1_LOC                                            {BA16} \
  CONFIG.VAUXP2_LOC                                            {AW17} \
  CONFIG.VAUXP3_LOC                                            {AV20} \
  CONFIG.VAUXP4_LOC                                            {BC21} \
  CONFIG.VAUXP5_LOC                                            {BD20} \
  CONFIG.VAUXP6_LOC                                            {BC17} \
  CONFIG.VAUXP7_LOC                                            {BD18} \
  CONFIG.VAUXP8_LOC                                            {AY16} \
  CONFIG.VAUXP9_LOC                                            {BB15} \
  CONFIG.VBRAM_ALARM_LOWER                                     {0.86} \
  CONFIG.VBRAM_ALARM_UPPER                                     {0.92} \
  CONFIG.VCCAUX_ALARM                                          {false} \
  CONFIG.VCCAUX_ALARM_LOWER                                    {1.75} \
  CONFIG.VCCAUX_ALARM_UPPER                                    {1.89} \
  CONFIG.VCCDDRO_ALARM_LOWER                                   {1.2} \
  CONFIG.VCCDDRO_ALARM_UPPER                                   {1.25} \
  CONFIG.VCCDDRO_VOLT                                          {1_2} \
  CONFIG.VCCINT_ALARM                                          {false} \
  CONFIG.VCCINT_ALARM_LOWER                                    {0.86} \
  CONFIG.VCCINT_ALARM_UPPER                                    {0.92} \
  CONFIG.VCCPAUX_ALARM_LOWER                                   {1.71} \
  CONFIG.VCCPAUX_ALARM_UPPER                                   {1.8} \
  CONFIG.VCCPINT_ALARM_LOWER                                   {0.95} \
  CONFIG.VCCPINT_ALARM_UPPER                                   {1.00} \
  CONFIG.VCCPSAUX_ALARM                                        {false} \
  CONFIG.VCCPSAUX_ALARM_LOWER                                  {1.71} \
  CONFIG.VCCPSAUX_ALARM_UPPER                                  {1.81} \
  CONFIG.VCCPSINTFP_ALARM                                      {false} \
  CONFIG.VCCPSINTFP_ALARM_LOWER                                {0.81} \
  CONFIG.VCCPSINTFP_ALARM_UPPER                                {0.86} \
  CONFIG.VCCPSINTLP_ALARM                                      {false} \
  CONFIG.VCCPSINTLP_ALARM_LOWER                                {0.81} \
  CONFIG.VCCPSINTLP_ALARM_UPPER                                {0.86} \
  CONFIG.WAVEFORM_TYPE                                         {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_TEMP                                    {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP0                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP1                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP10                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP11                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP12                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP13                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP14                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP15                                 {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP2                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP3                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP4                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP5                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP6                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP7                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP8                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VAUXP9                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VCCAUX                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VCCINT                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VCCPSAUX                                {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VCCPSINTFP                              {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VCCPSINTLP                              {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VP                                      {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VUSER0                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VUSER1                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VUSER2                                  {CONSTANT} \
  CONFIG.WAVEFORM_TYPE_VUSER3                                  {CONSTANT} \
]

