# *************************************************************************
# Auto-generated IP creation script for aurora_64b66b_0
# Source IP : xilinx.com:ip:aurora_64b66b:13.0
# Generated : 2026-04-29 21:21:38
# *************************************************************************

create_ip -name aurora_64b66b \
          -vendor xilinx.com \
          -library ip \
          -version 13.0 \
          -module_name aurora_64b66b_0

set_ip_properties_safe aurora_64b66b_0 [list \
  CONFIG.AXILITE_DRP_IF_0.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_1.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_10.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_11.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_12.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_13.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_14.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_15.INSERT_VIP                          {0} \
  CONFIG.AXILITE_DRP_IF_2.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_3.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_4.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_5.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_6.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_7.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_8.INSERT_VIP                           {0} \
  CONFIG.AXILITE_DRP_IF_9.INSERT_VIP                           {0} \
  CONFIG.CHANNEL_ENABLE                                        {X0Y28 X0Y29 X0Y30 X0Y31} \
  CONFIG.C_AURORA_LANES                                        {4} \
  CONFIG.C_COLUMN_USED                                         {left} \
  CONFIG.C_DOCCPORT_ENABLE                                     {false} \
  CONFIG.C_EXAMPLE_SIMULATION                                  {false} \
  CONFIG.C_GTWIZ_OUT                                           {false} \
  CONFIG.C_GT_CLOCK_1                                          {GTYQ0} \
  CONFIG.C_GT_CLOCK_2                                          {None} \
  CONFIG.C_GT_CLOCK_3                                          {None} \
  CONFIG.C_GT_CLOCK_4                                          {None} \
  CONFIG.C_GT_CLOCK_5                                          {None} \
  CONFIG.C_GT_LOC_1                                            {1} \
  CONFIG.C_GT_LOC_10                                           {X} \
  CONFIG.C_GT_LOC_11                                           {X} \
  CONFIG.C_GT_LOC_12                                           {X} \
  CONFIG.C_GT_LOC_13                                           {X} \
  CONFIG.C_GT_LOC_14                                           {X} \
  CONFIG.C_GT_LOC_15                                           {X} \
  CONFIG.C_GT_LOC_16                                           {X} \
  CONFIG.C_GT_LOC_17                                           {X} \
  CONFIG.C_GT_LOC_18                                           {X} \
  CONFIG.C_GT_LOC_19                                           {X} \
  CONFIG.C_GT_LOC_2                                            {2} \
  CONFIG.C_GT_LOC_20                                           {X} \
  CONFIG.C_GT_LOC_21                                           {X} \
  CONFIG.C_GT_LOC_22                                           {X} \
  CONFIG.C_GT_LOC_23                                           {X} \
  CONFIG.C_GT_LOC_24                                           {X} \
  CONFIG.C_GT_LOC_25                                           {X} \
  CONFIG.C_GT_LOC_26                                           {X} \
  CONFIG.C_GT_LOC_27                                           {X} \
  CONFIG.C_GT_LOC_28                                           {X} \
  CONFIG.C_GT_LOC_29                                           {X} \
  CONFIG.C_GT_LOC_3                                            {3} \
  CONFIG.C_GT_LOC_30                                           {X} \
  CONFIG.C_GT_LOC_31                                           {X} \
  CONFIG.C_GT_LOC_32                                           {X} \
  CONFIG.C_GT_LOC_33                                           {X} \
  CONFIG.C_GT_LOC_34                                           {X} \
  CONFIG.C_GT_LOC_35                                           {X} \
  CONFIG.C_GT_LOC_36                                           {X} \
  CONFIG.C_GT_LOC_37                                           {X} \
  CONFIG.C_GT_LOC_38                                           {X} \
  CONFIG.C_GT_LOC_39                                           {X} \
  CONFIG.C_GT_LOC_4                                            {4} \
  CONFIG.C_GT_LOC_40                                           {X} \
  CONFIG.C_GT_LOC_41                                           {X} \
  CONFIG.C_GT_LOC_42                                           {X} \
  CONFIG.C_GT_LOC_43                                           {X} \
  CONFIG.C_GT_LOC_44                                           {X} \
  CONFIG.C_GT_LOC_45                                           {X} \
  CONFIG.C_GT_LOC_46                                           {X} \
  CONFIG.C_GT_LOC_47                                           {X} \
  CONFIG.C_GT_LOC_48                                           {X} \
  CONFIG.C_GT_LOC_5                                            {X} \
  CONFIG.C_GT_LOC_6                                            {X} \
  CONFIG.C_GT_LOC_7                                            {X} \
  CONFIG.C_GT_LOC_8                                            {X} \
  CONFIG.C_GT_LOC_9                                            {X} \
  CONFIG.C_GT_TYPE                                             {GTY} \
  CONFIG.C_INIT_CLK                                            {100} \
  CONFIG.C_INT_DEBUG                                           {true} \
  CONFIG.C_LINE_RATE                                           {10.3125} \
  CONFIG.C_NEW_WIZ_MODE                                        {false} \
  CONFIG.C_PLL_TYPE                                            {LCPLL} \
  CONFIG.C_REFCLK2_SOURCE                                      {None} \
  CONFIG.C_REFCLK3_SOURCE                                      {None} \
  CONFIG.C_REFCLK4_SOURCE                                      {None} \
  CONFIG.C_REFCLK5_SOURCE                                      {None} \
  CONFIG.C_REFCLK_FREQUENCY                                    {156.25} \
  CONFIG.C_REFCLK_FREQUENCY_ACTUAL                             {156.250} \
  CONFIG.C_REFCLK_FREQUENCY_VERSAL                             {156.250} \
  CONFIG.C_REFCLK_SOURCE                                       {MGTREFCLK0_of_Quad_X0Y7} \
  CONFIG.C_START_LANE                                          {X0Y28} \
  CONFIG.C_START_QUAD                                          {Quad_X0Y7} \
  CONFIG.C_UCOLUMN_USED                                        {left} \
  CONFIG.C_USER_K                                              {true} \
  CONFIG.C_USE_BYTESWAP                                        {false} \
  CONFIG.C_USE_CHIPSCOPE                                       {false} \
  CONFIG.C_active_transceiverquads                             {1} \
  CONFIG.Component_Name                                        {aurora_64b66b_0} \
  CONFIG.DRP_FREQ                                              {100.0000} \
  CONFIG.GT_DRP_CLK_IN.INSERT_VIP                              {0} \
  CONFIG.GT_QPLLCLK_QUAD10_IN.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD10_OUT.INSERT_VIP                      {0} \
  CONFIG.GT_QPLLCLK_QUAD11_IN.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD11_OUT.INSERT_VIP                      {0} \
  CONFIG.GT_QPLLCLK_QUAD12_IN.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD12_OUT.INSERT_VIP                      {0} \
  CONFIG.GT_QPLLCLK_QUAD1_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD1_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD2_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD2_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD3_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD3_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD4_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD4_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD5_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD5_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD6_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD6_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD7_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD7_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD8_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD8_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLCLK_QUAD9_IN.INSERT_VIP                        {0} \
  CONFIG.GT_QPLLCLK_QUAD9_OUT.INSERT_VIP                       {0} \
  CONFIG.GT_QPLLREFCLK_QUAD10_IN.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD10_OUT.INSERT_VIP                   {0} \
  CONFIG.GT_QPLLREFCLK_QUAD11_IN.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD11_OUT.INSERT_VIP                   {0} \
  CONFIG.GT_QPLLREFCLK_QUAD12_IN.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD12_OUT.INSERT_VIP                   {0} \
  CONFIG.GT_QPLLREFCLK_QUAD1_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD1_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD2_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD2_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD3_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD3_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD4_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD4_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD5_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD5_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD6_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD6_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD7_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD7_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD8_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD8_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_QPLLREFCLK_QUAD9_IN.INSERT_VIP                     {0} \
  CONFIG.GT_QPLLREFCLK_QUAD9_OUT.INSERT_VIP                    {0} \
  CONFIG.GT_REFCLK1_OUT.INSERT_VIP                             {0} \
  CONFIG.GT_REFCLK2_OUT.INSERT_VIP                             {0} \
  CONFIG.GT_REFCLK3_OUT.INSERT_VIP                             {0} \
  CONFIG.GT_REFCLK4_OUT.INSERT_VIP                             {0} \
  CONFIG.GT_REFCLK5_OUT.INSERT_VIP                             {0} \
  CONFIG.GT_RESET.INSERT_VIP                                   {0} \
  CONFIG.GT_RESET_OUT.INSERT_VIP                               {0} \
  CONFIG.GT_RXUSRCLK_OUT.INSERT_VIP                            {0} \
  CONFIG.INIT_CLK_IN.INSERT_VIP                                {0} \
  CONFIG.INIT_CLK_OUT.INSERT_VIP                               {0} \
  CONFIG.INS_LOSS_NYQ                                          {20} \
  CONFIG.LINK_RESET_OUT.INSERT_VIP                             {0} \
  CONFIG.NFC_S_AXIS_TX.INSERT_VIP                              {0} \
  CONFIG.REFCLK1_IN.INSERT_VIP                                 {0} \
  CONFIG.REFCLK2_IN.INSERT_VIP                                 {0} \
  CONFIG.REFCLK3_IN.INSERT_VIP                                 {0} \
  CONFIG.REFCLK4_IN.INSERT_VIP                                 {0} \
  CONFIG.REFCLK5_IN.INSERT_VIP                                 {0} \
  CONFIG.RESET2FC.INSERT_VIP                                   {0} \
  CONFIG.RESET2FG.INSERT_VIP                                   {0} \
  CONFIG.RESET_PB.INSERT_VIP                                   {0} \
  CONFIG.RX_COUPLING                                           {AC} \
  CONFIG.RX_EQ_MODE                                            {AUTO} \
  CONFIG.RX_PPM_OFFSET                                         {0} \
  CONFIG.RX_RESET_PB.INSERT_VIP                                {0} \
  CONFIG.RX_SSC_PPM                                            {0} \
  CONFIG.RX_SYS_RESET_OUT.INSERT_VIP                           {0} \
  CONFIG.RX_TERMINATION                                        {PROGRAMMABLE} \
  CONFIG.RX_TERMINATION_PROG_VALUE                             {800} \
  CONFIG.SINGLEEND_GTREFCLK                                    {false} \
  CONFIG.SINGLEEND_INITCLK                                     {true} \
  CONFIG.SYNC_CLK.INSERT_VIP                                   {0} \
  CONFIG.SYNC_CLK_OUT.INSERT_VIP                               {0} \
  CONFIG.SYS_RESET_OUT.INSERT_VIP                              {0} \
  CONFIG.SupportLevel                                          {1} \
  CONFIG.TX_OUT_CLK.INSERT_VIP                                 {0} \
  CONFIG.TX_RESET_PB.INSERT_VIP                                {0} \
  CONFIG.TX_SYS_RESET_OUT.INSERT_VIP                           {0} \
  CONFIG.TransceiverControl                                    {true} \
  CONFIG.UFC_M_AXIS_RX.INSERT_VIP                              {0} \
  CONFIG.UFC_S_AXIS_TX.INSERT_VIP                              {0} \
  CONFIG.USER_CLK.INSERT_VIP                                   {0} \
  CONFIG.USER_CLK_2.INSERT_VIP                                 {0} \
  CONFIG.USER_CLK_OUT.INSERT_VIP                               {0} \
  CONFIG.USER_DATA_M_AXIS_RX.INSERT_VIP                        {0} \
  CONFIG.USER_DATA_S_AXIS_TX.INSERT_VIP                        {0} \
  CONFIG.USER_K_M_AXIS_RX.INSERT_VIP                           {0} \
  CONFIG.USER_K_S_AXIS_TX.INSERT_VIP                           {0} \
  CONFIG.crc_mode                                              {true} \
  CONFIG.dataflow_config                                       {Duplex} \
  CONFIG.drp_mode                                              {AXI4_LITE} \
  CONFIG.flow_mode                                             {None} \
  CONFIG.interface_mode                                        {Framing} \
]

