# *************************************************************************
# Auto-generated IP creation script for xdma_0
# Source IP : xilinx.com:ip:xdma:4.2
# Generated : 2026-04-16 10:11:41
# *************************************************************************

create_ip -name xdma \
          -vendor xilinx.com \
          -library ip \
          -version 4.2 \
          -module_name xdma_0

set_ip_properties_safe xdma_0 [list \
  CONFIG.ATSPRI_M_AXIS_CQ.INSERT_VIP                           {0} \
  CONFIG.ATSPRI_S_AXIS_RQ.INSERT_VIP                           {0} \
  CONFIG.BASEADDR                                              {0x00001000} \
  CONFIG.CLK.AXI_ACLK.INSERT_VIP                               {0} \
  CONFIG.CLK.AXI_CTL_ACLK.INSERT_VIP                           {0} \
  CONFIG.CLK.CORE_CLK.INSERT_VIP                               {0} \
  CONFIG.CLK.EXT_CH_GT_DRPCLK.INSERT_VIP                       {0} \
  CONFIG.CLK.GT_DRP_CLK.INSERT_VIP                             {0} \
  CONFIG.CLK.SYS_CLK.INSERT_VIP                                {0} \
  CONFIG.CLK.SYS_CLK_GT.INSERT_VIP                             {0} \
  CONFIG.CLK.S_ACLK.INSERT_VIP                                 {0} \
  CONFIG.CLK.USER_CLK.INSERT_VIP                               {0} \
  CONFIG.Component_Name                                        {xdma_0} \
  CONFIG.EGW_IS_PARENT_IP                                      {1} \
  CONFIG.HIGHADDR                                              {0x00001FFF} \
  CONFIG.INS_LOSS_NYQ                                          {15} \
  CONFIG.MSI_X_OPTIONS                                         {None} \
  CONFIG.M_AXI.INSERT_VIP                                      {0} \
  CONFIG.M_AXIS_CQ.INSERT_VIP                                  {0} \
  CONFIG.M_AXIS_H2C_0.INSERT_VIP                               {0} \
  CONFIG.M_AXIS_H2C_1.INSERT_VIP                               {0} \
  CONFIG.M_AXIS_H2C_2.INSERT_VIP                               {0} \
  CONFIG.M_AXIS_H2C_3.INSERT_VIP                               {0} \
  CONFIG.M_AXIS_RC.INSERT_VIP                                  {0} \
  CONFIG.M_AXI_B.INSERT_VIP                                    {0} \
  CONFIG.M_AXI_BYPASS.INSERT_VIP                               {0} \
  CONFIG.M_AXI_LITE.INSERT_VIP                                 {0} \
  CONFIG.PCIE_BOARD_INTERFACE                                  {pci_express_x16} \
  CONFIG.PF0_DEVICE_ID_mqdma                                   {903F} \
  CONFIG.PF0_MSIX_CAP_PBA_BIR_mqdma                            {BAR_0} \
  CONFIG.PF0_MSIX_CAP_PBA_OFFSET_mqdma                         {00000000} \
  CONFIG.PF0_MSIX_CAP_TABLE_BIR_mqdma                          {BAR_0} \
  CONFIG.PF0_MSIX_CAP_TABLE_OFFSET_mqdma                       {00000000} \
  CONFIG.PF0_MSIX_CAP_TABLE_SIZE_mqdma                         {000} \
  CONFIG.PF0_REVISION_ID_mqdma                                 {00} \
  CONFIG.PF0_SRIOV_CAP_INITIAL_VF                              {0} \
  CONFIG.PF0_SRIOV_FIRST_VF_OFFSET                             {0} \
  CONFIG.PF0_SRIOV_FUNC_DEP_LINK                               {0000} \
  CONFIG.PF0_SRIOV_SUPPORTED_PAGE_SIZE                         {00000553} \
  CONFIG.PF0_SRIOV_VF_DEVICE_ID                                {A03F} \
  CONFIG.PF0_SUBSYSTEM_ID_mqdma                                {0007} \
  CONFIG.PF0_SUBSYSTEM_VENDOR_ID_mqdma                         {10EE} \
  CONFIG.PF1_DEVICE_ID_mqdma                                   {0007} \
  CONFIG.PF1_INTERRUPT_PIN                                     {NONE} \
  CONFIG.PF1_MSIX_CAP_PBA_BIR_mqdma                            {BAR_0} \
  CONFIG.PF1_MSIX_CAP_PBA_OFFSET_mqdma                         {00000000} \
  CONFIG.PF1_MSIX_CAP_TABLE_BIR_mqdma                          {BAR_0} \
  CONFIG.PF1_MSIX_CAP_TABLE_OFFSET_mqdma                       {00000000} \
  CONFIG.PF1_MSIX_CAP_TABLE_SIZE_mqdma                         {000} \
  CONFIG.PF1_MSI_CAP_MULTIMSGCAP                               {1_vector} \
  CONFIG.PF1_REVISION_ID                                       {00} \
  CONFIG.PF1_REVISION_ID_mqdma                                 {00} \
  CONFIG.PF1_SRIOV_CAP_INITIAL_VF                              {0} \
  CONFIG.PF1_SRIOV_CAP_VER                                     {1} \
  CONFIG.PF1_SRIOV_FIRST_VF_OFFSET                             {0} \
  CONFIG.PF1_SRIOV_FUNC_DEP_LINK                               {0001} \
  CONFIG.PF1_SRIOV_SUPPORTED_PAGE_SIZE                         {00000553} \
  CONFIG.PF1_SRIOV_VF_DEVICE_ID                                {A13F} \
  CONFIG.PF1_SUBSYSTEM_ID                                      {0007} \
  CONFIG.PF1_SUBSYSTEM_ID_mqdma                                {0007} \
  CONFIG.PF1_SUBSYSTEM_VENDOR_ID                               {10EE} \
  CONFIG.PF1_SUBSYSTEM_VENDOR_ID_mqdma                         {10EE} \
  CONFIG.PF1_Use_Class_Code_Lookup_Assistant                   {false} \
  CONFIG.PF2_DEVICE_ID_mqdma                                   {923F} \
  CONFIG.PF2_INTERRUPT_PIN                                     {NONE} \
  CONFIG.PF2_MSIX_CAP_PBA_BIR_mqdma                            {BAR_0} \
  CONFIG.PF2_MSIX_CAP_PBA_OFFSET_mqdma                         {00000000} \
  CONFIG.PF2_MSIX_CAP_TABLE_BIR_mqdma                          {BAR_0} \
  CONFIG.PF2_MSIX_CAP_TABLE_OFFSET_mqdma                       {00000000} \
  CONFIG.PF2_MSIX_CAP_TABLE_SIZE_mqdma                         {000} \
  CONFIG.PF2_MSI_CAP_MULTIMSGCAP                               {1_vector} \
  CONFIG.PF2_REVISION_ID                                       {00} \
  CONFIG.PF2_REVISION_ID_mqdma                                 {00} \
  CONFIG.PF2_SRIOV_CAP_INITIAL_VF                              {0} \
  CONFIG.PF2_SRIOV_CAP_VER                                     {1} \
  CONFIG.PF2_SRIOV_FIRST_VF_OFFSET                             {0} \
  CONFIG.PF2_SRIOV_FUNC_DEP_LINK                               {0002} \
  CONFIG.PF2_SRIOV_SUPPORTED_PAGE_SIZE                         {00000553} \
  CONFIG.PF2_SRIOV_VF_DEVICE_ID                                {A23F} \
  CONFIG.PF2_SUBSYSTEM_ID                                      {0007} \
  CONFIG.PF2_SUBSYSTEM_ID_mqdma                                {0007} \
  CONFIG.PF2_SUBSYSTEM_VENDOR_ID                               {10EE} \
  CONFIG.PF2_SUBSYSTEM_VENDOR_ID_mqdma                         {10EE} \
  CONFIG.PF2_Use_Class_Code_Lookup_Assistant                   {false} \
  CONFIG.PF3_DEVICE_ID_mqdma                                   {933F} \
  CONFIG.PF3_INTERRUPT_PIN                                     {NONE} \
  CONFIG.PF3_MSIX_CAP_PBA_BIR_mqdma                            {BAR_0} \
  CONFIG.PF3_MSIX_CAP_PBA_OFFSET_mqdma                         {00000000} \
  CONFIG.PF3_MSIX_CAP_TABLE_BIR_mqdma                          {BAR_0} \
  CONFIG.PF3_MSIX_CAP_TABLE_OFFSET_mqdma                       {00000000} \
  CONFIG.PF3_MSIX_CAP_TABLE_SIZE_mqdma                         {000} \
  CONFIG.PF3_MSI_CAP_MULTIMSGCAP                               {1_vector} \
  CONFIG.PF3_REVISION_ID                                       {00} \
  CONFIG.PF3_REVISION_ID_mqdma                                 {00} \
  CONFIG.PF3_SRIOV_CAP_INITIAL_VF                              {0} \
  CONFIG.PF3_SRIOV_CAP_VER                                     {1} \
  CONFIG.PF3_SRIOV_FIRST_VF_OFFSET                             {0} \
  CONFIG.PF3_SRIOV_FUNC_DEP_LINK                               {0003} \
  CONFIG.PF3_SRIOV_SUPPORTED_PAGE_SIZE                         {00000553} \
  CONFIG.PF3_SRIOV_VF_DEVICE_ID                                {A33F} \
  CONFIG.PF3_SUBSYSTEM_ID                                      {0007} \
  CONFIG.PF3_SUBSYSTEM_ID_mqdma                                {0007} \
  CONFIG.PF3_SUBSYSTEM_VENDOR_ID                               {10EE} \
  CONFIG.PF3_SUBSYSTEM_VENDOR_ID_mqdma                         {10EE} \
  CONFIG.PF3_Use_Class_Code_Lookup_Assistant                   {false} \
  CONFIG.PHY_LP_TXPRESET                                       {4} \
  CONFIG.PS_TYPE_IN                                            {PS9} \
  CONFIG.RST.AXI_ARESETN.INSERT_VIP                            {0} \
  CONFIG.RST.AXI_CTL_ARESETN.INSERT_VIP                        {0} \
  CONFIG.RST.SYS_RST_N.INSERT_VIP                              {0} \
  CONFIG.RST.S_ARESETN.INSERT_VIP                              {0} \
  CONFIG.RST.USER_RESET.INSERT_VIP                             {0} \
  CONFIG.RX_PPM_OFFSET                                         {0} \
  CONFIG.RX_SSC_PPM                                            {0} \
  CONFIG.SC0_ATS_M_AXIS_CQ.INSERT_VIP                          {0} \
  CONFIG.SC0_ATS_M_AXIS_RC.INSERT_VIP                          {0} \
  CONFIG.SC0_ATS_S_AXIS_CC.INSERT_VIP                          {0} \
  CONFIG.SC0_ATS_S_AXIS_RQ.INSERT_VIP                          {0} \
  CONFIG.SC1_ATS_M_AXIS_CQ.INSERT_VIP                          {0} \
  CONFIG.SC1_ATS_M_AXIS_RC.INSERT_VIP                          {0} \
  CONFIG.SC1_ATS_S_AXIS_CC.INSERT_VIP                          {0} \
  CONFIG.SC1_ATS_S_AXIS_RQ.INSERT_VIP                          {0} \
  CONFIG.SRIOV_CAP_ENABLE                                      {false} \
  CONFIG.SRIOV_FIRST_VF_OFFSET                                 {1} \
  CONFIG.SYS_RST_N_BOARD_INTERFACE                             {pcie_perstn} \
  CONFIG.S_AXI.INSERT_VIP                                      {0} \
  CONFIG.S_AXIS_C2H_0.INSERT_VIP                               {0} \
  CONFIG.S_AXIS_C2H_1.INSERT_VIP                               {0} \
  CONFIG.S_AXIS_C2H_2.INSERT_VIP                               {0} \
  CONFIG.S_AXIS_C2H_3.INSERT_VIP                               {0} \
  CONFIG.S_AXIS_CC.INSERT_VIP                                  {0} \
  CONFIG.S_AXIS_RQ.INSERT_VIP                                  {0} \
  CONFIG.S_AXI_B.INSERT_VIP                                    {0} \
  CONFIG.S_AXI_LITE.INSERT_VIP                                 {0} \
  CONFIG.Shared_Logic                                          {1} \
  CONFIG.Shared_Logic_Both                                     {false} \
  CONFIG.Shared_Logic_Both_7xG2                                {false} \
  CONFIG.Shared_Logic_Clk                                      {false} \
  CONFIG.Shared_Logic_Clk_7xG2                                 {false} \
  CONFIG.Shared_Logic_Gtc                                      {false} \
  CONFIG.Shared_Logic_Gtc_7xG2                                 {false} \
  CONFIG.acs_ext_cap_enable                                    {false} \
  CONFIG.all_speeds_all_sides                                  {NO} \
  CONFIG.aspm_support                                          {No_ASPM} \
  CONFIG.axi_aclk_loopback                                     {false} \
  CONFIG.axi_addr_width                                        {64} \
  CONFIG.axi_bypass_64bit_en                                   {false} \
  CONFIG.axi_bypass_prefetchable                               {false} \
  CONFIG.axi_data_width                                        {512_bit} \
  CONFIG.axi_id_width                                          {4} \
  CONFIG.axi_vip_in_exdes                                      {false} \
  CONFIG.axibar2pciebar_0                                      {0x0000000000000000} \
  CONFIG.axibar2pciebar_1                                      {0x0000000000000000} \
  CONFIG.axibar2pciebar_2                                      {0x0000000000000000} \
  CONFIG.axibar2pciebar_3                                      {0x0000000000000000} \
  CONFIG.axibar2pciebar_4                                      {0x0000000000000000} \
  CONFIG.axibar2pciebar_5                                      {0x0000000000000000} \
  CONFIG.axibar_0                                              {0x0000000000000000} \
  CONFIG.axibar_1                                              {0x0000000000000000} \
  CONFIG.axibar_2                                              {0x0000000000000000} \
  CONFIG.axibar_3                                              {0x0000000000000000} \
  CONFIG.axibar_4                                              {0x0000000000000000} \
  CONFIG.axibar_5                                              {0x0000000000000000} \
  CONFIG.axibar_highaddr_0                                     {0x0000000000000000} \
  CONFIG.axibar_highaddr_1                                     {0x0000000000000000} \
  CONFIG.axibar_highaddr_2                                     {0x0000000000000000} \
  CONFIG.axibar_highaddr_3                                     {0x0000000000000000} \
  CONFIG.axibar_highaddr_4                                     {0x0000000000000000} \
  CONFIG.axibar_highaddr_5                                     {0x0000000000000000} \
  CONFIG.axibar_num                                            {1} \
  CONFIG.axil_master_64bit_en                                  {false} \
  CONFIG.axil_master_prefetchable                              {false} \
  CONFIG.axilite_master_en                                     {true} \
  CONFIG.axilite_master_scale                                  {Megabytes} \
  CONFIG.axilite_master_size                                   {1} \
  CONFIG.axis_pipe_line_stage                                  {0} \
  CONFIG.axist_bypass_en                                       {false} \
  CONFIG.axist_bypass_scale                                    {Megabytes} \
  CONFIG.axist_bypass_size                                     {1} \
  CONFIG.axisten_freq                                          {250} \
  CONFIG.axisten_if_enable_msg_route                           {27FFF} \
  CONFIG.axsize_byte_access_en                                 {false} \
  CONFIG.bar0_indicator                                        {1} \
  CONFIG.bar1_indicator                                        {0} \
  CONFIG.bar2_indicator                                        {0} \
  CONFIG.bar3_indicator                                        {0} \
  CONFIG.bar4_indicator                                        {0} \
  CONFIG.bar5_indicator                                        {0} \
  CONFIG.bar_indicator                                         {BAR_1:0} \
  CONFIG.barlite2                                              {7} \
  CONFIG.bridge_burst                                          {false} \
  CONFIG.bridge_registers_offset_enable                        {false} \
  CONFIG.c_ats_enable                                          {false} \
  CONFIG.c_ats_switch_unique_bdf                               {1} \
  CONFIG.c_m_axi_num_read                                      {8} \
  CONFIG.c_m_axi_num_readq                                     {2} \
  CONFIG.c_m_axi_num_write                                     {8} \
  CONFIG.c_pri_enable                                          {false} \
  CONFIG.c_s_axi_num_read                                      {8} \
  CONFIG.c_s_axi_num_write                                     {8} \
  CONFIG.c_s_axi_supports_narrow_burst                         {false} \
  CONFIG.c_smmu_en                                             {0} \
  CONFIG.cfg_ext_if                                            {false} \
  CONFIG.cfg_mgmt_if                                           {true} \
  CONFIG.cfg_space_enable                                      {false} \
  CONFIG.comp_timeout                                          {50ms} \
  CONFIG.copy_pf0                                              {false} \
  CONFIG.copy_sriov_pf0                                        {true} \
  CONFIG.coreclk_freq                                          {500} \
  CONFIG.ctrl_skip_mask                                        {true} \
  CONFIG.dedicate_perst                                        {false} \
  CONFIG.descriptor_bypass_exdes                               {false} \
  CONFIG.device_port_type                                      {PCI_Express_Endpoint_device} \
  CONFIG.disable_bram_pipeline                                 {false} \
  CONFIG.disable_eq_synchronizer                               {false} \
  CONFIG.disable_gt_loc                                        {false} \
  CONFIG.disable_speed_width_drc                               {false} \
  CONFIG.disable_user_clock_root                               {true} \
  CONFIG.dma_2rp                                               {false} \
  CONFIG.dma_reset_source_sel                                  {User_Reset} \
  CONFIG.drp_clk_sel                                           {Internal} \
  CONFIG.dsc_bypass_rd                                         {0000} \
  CONFIG.dsc_bypass_rd_out                                     {0000} \
  CONFIG.dsc_bypass_wr                                         {0000} \
  CONFIG.dsc_bypass_wr_out                                     {0000} \
  CONFIG.ecc_en                                                {false} \
  CONFIG.en_axi_master_if                                      {true} \
  CONFIG.en_axi_mm_mqdma                                       {true} \
  CONFIG.en_axi_slave_if                                       {true} \
  CONFIG.en_axi_st_mqdma                                       {false} \
  CONFIG.en_bridge                                             {false} \
  CONFIG.en_bridge_slv                                         {false} \
  CONFIG.en_coreclk_es1                                        {false} \
  CONFIG.en_dbg_descramble                                     {false} \
  CONFIG.en_debug_ports                                        {false} \
  CONFIG.en_dma_and_bridge                                     {false} \
  CONFIG.en_ext_ch_gt_drp                                      {false} \
  CONFIG.en_gt_selection                                       {true} \
  CONFIG.en_l23_entry                                          {false} \
  CONFIG.en_mqdma                                              {false} \
  CONFIG.en_pcie_drp                                           {false} \
  CONFIG.en_slot_cap_reg                                       {false} \
  CONFIG.en_transceiver_status_ports                           {true} \
  CONFIG.enable_ats_switch                                     {FALSE} \
  CONFIG.enable_auto_rxeq                                      {False} \
  CONFIG.enable_ccix                                           {FALSE} \
  CONFIG.enable_clock_delay_grp                                {true} \
  CONFIG.enable_code                                           {0000} \
  CONFIG.enable_dvsec                                          {FALSE} \
  CONFIG.enable_epyc_chipset_fix                               {false} \
  CONFIG.enable_error_injection                                {false} \
  CONFIG.enable_gen4                                           {true} \
  CONFIG.enable_gen4_low_sp_gra                                {false} \
  CONFIG.enable_gtwizard                                       {true} \
  CONFIG.enable_ibert                                          {false} \
  CONFIG.enable_jtag_dbg                                       {false} \
  CONFIG.enable_lane_reversal                                  {false} \
  CONFIG.enable_ltssm_dbg                                      {false} \
  CONFIG.enable_mark_debug                                     {false} \
  CONFIG.enable_more_clk                                       {false} \
  CONFIG.enable_multi_pcie                                     {false} \
  CONFIG.enable_pcie_debug                                     {False} \
  CONFIG.enable_pcie_debug_axi4_st                             {False} \
  CONFIG.enable_pcie_debug_ports                               {False} \
  CONFIG.enable_resource_reduction                             {false} \
  CONFIG.enable_slave_read_64os                                {false} \
  CONFIG.enh_xdma_en                                           {false} \
  CONFIG.errc_dec_en                                           {false} \
  CONFIG.example_design_type                                   {RTL} \
  CONFIG.exdes_flow                                            {false} \
  CONFIG.ext_startup_primitive                                 {false} \
  CONFIG.ext_sys_clk_bufg                                      {false} \
  CONFIG.ext_xvc_vsec_enable                                   {false} \
  CONFIG.flr_enable                                            {false} \
  CONFIG.free_run_freq                                         {100_MHz} \
  CONFIG.functional_mode                                       {DMA} \
  CONFIG.gen4_eieos_0s7                                        {true} \
  CONFIG.gen_pipe_debug                                        {false} \
  CONFIG.gt_available                                          {GTY_QUAD_X0Y0} \
  CONFIG.gt_loc_num                                            {X99Y99} \
  CONFIG.gt_selected                                           {GTY_QUAD_X0Y0} \
  CONFIG.gtcom_in_core_usp                                     {2} \
  CONFIG.gtwiz_in_core_us                                      {1} \
  CONFIG.gtwiz_in_core_usp                                     {1} \
  CONFIG.include_baroffset_reg                                 {true} \
  CONFIG.ins_loss_profile                                      {Add-in_Card} \
  CONFIG.insert_cips                                           {false} \
  CONFIG.intx_rx_pin_en                                        {true} \
  CONFIG.lane_order                                            {Bottom} \
  CONFIG.legacy_cfg_ext_if                                     {false} \
  CONFIG.local_test                                            {false} \
  CONFIG.m_axib_num_write_scale                                {1} \
  CONFIG.master_cal_only                                       {false} \
  CONFIG.mcap_enablement                                       {None} \
  CONFIG.mcap_fpga_bitstream_version                           {00000000} \
  CONFIG.mode_selection                                        {Advanced} \
  CONFIG.mpsoc_pl_rp_enable                                    {false} \
  CONFIG.msi_rx_pin_en                                         {FALSE} \
  CONFIG.msix_pcie_internal                                    {false} \
  CONFIG.msix_rx_decode_en                                     {FALSE} \
  CONFIG.msix_rx_pin_en                                        {TRUE} \
  CONFIG.msix_type                                             {HARD} \
  CONFIG.mult_pf_des                                           {false} \
  CONFIG.num_queues                                            {1} \
  CONFIG.old_bridge_timeout                                    {false} \
  CONFIG.parity_settings                                       {None} \
  CONFIG.pcie_blk_locn                                         {PCIE4C_X1Y0} \
  CONFIG.pcie_extended_tag                                     {false} \
  CONFIG.pcie_id_if                                            {FALSE} \
  CONFIG.pciebar2axibar_0                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_1                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_2                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_3                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_4                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_5                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_6                                      {0x0000000000000000} \
  CONFIG.pciebar2axibar_axil_master                            {0x00000000} \
  CONFIG.pciebar2axibar_axist_bypass                           {0x0000000000000000} \
  CONFIG.pciebar2axibar_xdma                                   {0x0000000000000000} \
  CONFIG.performance                                           {false} \
  CONFIG.performance_exdes                                     {false} \
  CONFIG.pf0_Use_Class_Code_Lookup_Assistant                   {false} \
  CONFIG.pf0_Use_Class_Code_Lookup_Assistant_mqdma             {false} \
  CONFIG.pf0_aer_cap_ecrc_gen_and_check_capable                {false} \
  CONFIG.pf0_ari_enabled                                       {false} \
  CONFIG.pf0_ats_enabled                                       {false} \
  CONFIG.pf0_bar0_64bit                                        {true} \
  CONFIG.pf0_bar0_64bit_mqdma                                  {false} \
  CONFIG.pf0_bar0_enabled                                      {true} \
  CONFIG.pf0_bar0_enabled_mqdma                                {true} \
  CONFIG.pf0_bar0_index                                        {0} \
  CONFIG.pf0_bar0_prefetchable                                 {false} \
  CONFIG.pf0_bar0_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar0_scale                                        {Megabytes} \
  CONFIG.pf0_bar0_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar0_size                                         {16} \
  CONFIG.pf0_bar0_size_mqdma                                   {128} \
  CONFIG.pf0_bar0_type                                         {Memory} \
  CONFIG.pf0_bar0_type_mqdma                                   {DMA} \
  CONFIG.pf0_bar1_64bit                                        {false} \
  CONFIG.pf0_bar1_64bit_mqdma                                  {false} \
  CONFIG.pf0_bar1_enabled                                      {false} \
  CONFIG.pf0_bar1_enabled_mqdma                                {false} \
  CONFIG.pf0_bar1_index                                        {7} \
  CONFIG.pf0_bar1_prefetchable                                 {false} \
  CONFIG.pf0_bar1_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar1_scale                                        {Kilobytes} \
  CONFIG.pf0_bar1_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar1_size                                         {4} \
  CONFIG.pf0_bar1_size_mqdma                                   {128} \
  CONFIG.pf0_bar1_type                                         {Memory} \
  CONFIG.pf0_bar1_type_mqdma                                   {N/A} \
  CONFIG.pf0_bar2_64bit                                        {false} \
  CONFIG.pf0_bar2_64bit_mqdma                                  {false} \
  CONFIG.pf0_bar2_enabled                                      {false} \
  CONFIG.pf0_bar2_enabled_mqdma                                {false} \
  CONFIG.pf0_bar2_index                                        {7} \
  CONFIG.pf0_bar2_prefetchable                                 {false} \
  CONFIG.pf0_bar2_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar2_scale                                        {Kilobytes} \
  CONFIG.pf0_bar2_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar2_size                                         {4} \
  CONFIG.pf0_bar2_size_mqdma                                   {128} \
  CONFIG.pf0_bar2_type                                         {Memory} \
  CONFIG.pf0_bar2_type_mqdma                                   {N/A} \
  CONFIG.pf0_bar3_64bit                                        {false} \
  CONFIG.pf0_bar3_64bit_mqdma                                  {false} \
  CONFIG.pf0_bar3_enabled                                      {false} \
  CONFIG.pf0_bar3_enabled_mqdma                                {false} \
  CONFIG.pf0_bar3_index                                        {7} \
  CONFIG.pf0_bar3_prefetchable                                 {false} \
  CONFIG.pf0_bar3_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar3_scale                                        {Kilobytes} \
  CONFIG.pf0_bar3_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar3_size                                         {4} \
  CONFIG.pf0_bar3_size_mqdma                                   {128} \
  CONFIG.pf0_bar3_type                                         {Memory} \
  CONFIG.pf0_bar3_type_mqdma                                   {N/A} \
  CONFIG.pf0_bar4_64bit                                        {false} \
  CONFIG.pf0_bar4_64bit_mqdma                                  {false} \
  CONFIG.pf0_bar4_enabled                                      {false} \
  CONFIG.pf0_bar4_enabled_mqdma                                {false} \
  CONFIG.pf0_bar4_index                                        {7} \
  CONFIG.pf0_bar4_prefetchable                                 {false} \
  CONFIG.pf0_bar4_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar4_scale                                        {Kilobytes} \
  CONFIG.pf0_bar4_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar4_size                                         {4} \
  CONFIG.pf0_bar4_size_mqdma                                   {128} \
  CONFIG.pf0_bar4_type                                         {Memory} \
  CONFIG.pf0_bar4_type_mqdma                                   {N/A} \
  CONFIG.pf0_bar5_64bit                                        {false} \
  CONFIG.pf0_bar5_enabled                                      {false} \
  CONFIG.pf0_bar5_enabled_mqdma                                {false} \
  CONFIG.pf0_bar5_index                                        {7} \
  CONFIG.pf0_bar5_prefetchable                                 {false} \
  CONFIG.pf0_bar5_prefetchable_mqdma                           {false} \
  CONFIG.pf0_bar5_scale                                        {Kilobytes} \
  CONFIG.pf0_bar5_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf0_bar5_size                                         {4} \
  CONFIG.pf0_bar5_size_mqdma                                   {128} \
  CONFIG.pf0_bar5_type                                         {Memory} \
  CONFIG.pf0_bar5_type_mqdma                                   {N/A} \
  CONFIG.pf0_base_class_menu                                   {Simple_communication_controllers} \
  CONFIG.pf0_base_class_menu_mqdma                             {Memory_controller} \
  CONFIG.pf0_class_code                                        {070001} \
  CONFIG.pf0_class_code_base                                   {07} \
  CONFIG.pf0_class_code_base_mqdma                             {05} \
  CONFIG.pf0_class_code_interface                              {01} \
  CONFIG.pf0_class_code_interface_mqdma                        {00} \
  CONFIG.pf0_class_code_mqdma                                  {058000} \
  CONFIG.pf0_class_code_sub                                    {00} \
  CONFIG.pf0_class_code_sub_mqdma                              {80} \
  CONFIG.pf0_dev_cap2_10b_tag_completer_supported              {false} \
  CONFIG.pf0_device_id                                         {903F} \
  CONFIG.pf0_expansion_rom_enabled                             {false} \
  CONFIG.pf0_expansion_rom_scale                               {Kilobytes} \
  CONFIG.pf0_expansion_rom_size                                {4} \
  CONFIG.pf0_expansion_rom_type                                {N/A} \
  CONFIG.pf0_interrupt_pin                                     {INTA} \
  CONFIG.pf0_link_status_slot_clock_config                     {true} \
  CONFIG.pf0_msi_cap_multimsgcap                               {1_vector} \
  CONFIG.pf0_msi_enabled                                       {true} \
  CONFIG.pf0_msix_cap_pba_bir                                  {BAR_1} \
  CONFIG.pf0_msix_cap_pba_offset                               {00000000} \
  CONFIG.pf0_msix_cap_table_bir                                {BAR_1} \
  CONFIG.pf0_msix_cap_table_offset                             {00000000} \
  CONFIG.pf0_msix_cap_table_size                               {000} \
  CONFIG.pf0_msix_enabled                                      {false} \
  CONFIG.pf0_msix_enabled_mqdma                                {false} \
  CONFIG.pf0_msix_impl_locn                                    {Internal} \
  CONFIG.pf0_pm_cap_pmesupport_d0                              {false} \
  CONFIG.pf0_pm_cap_pmesupport_d1                              {false} \
  CONFIG.pf0_pm_cap_pmesupport_d3hot                           {false} \
  CONFIG.pf0_pm_cap_supp_d1_state                              {false} \
  CONFIG.pf0_pri_enabled                                       {false} \
  CONFIG.pf0_rbar_cap_bar0                                     {0x00000000fff0} \
  CONFIG.pf0_rbar_cap_bar1                                     {0x000000000000} \
  CONFIG.pf0_rbar_cap_bar2                                     {0x000000000000} \
  CONFIG.pf0_rbar_cap_bar3                                     {0x000000000000} \
  CONFIG.pf0_rbar_cap_bar4                                     {0x000000000000} \
  CONFIG.pf0_rbar_cap_bar5                                     {0x000000000000} \
  CONFIG.pf0_rbar_num                                          {1} \
  CONFIG.pf0_revision_id                                       {00} \
  CONFIG.pf0_sriov_bar0_64bit                                  {false} \
  CONFIG.pf0_sriov_bar0_enabled                                {true} \
  CONFIG.pf0_sriov_bar0_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar0_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar0_size                                   {2} \
  CONFIG.pf0_sriov_bar0_type                                   {DMA} \
  CONFIG.pf0_sriov_bar1_64bit                                  {false} \
  CONFIG.pf0_sriov_bar1_enabled                                {false} \
  CONFIG.pf0_sriov_bar1_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar1_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar1_size                                   {2} \
  CONFIG.pf0_sriov_bar1_type                                   {N/A} \
  CONFIG.pf0_sriov_bar2_64bit                                  {false} \
  CONFIG.pf0_sriov_bar2_enabled                                {false} \
  CONFIG.pf0_sriov_bar2_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar2_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar2_size                                   {2} \
  CONFIG.pf0_sriov_bar2_type                                   {N/A} \
  CONFIG.pf0_sriov_bar3_64bit                                  {false} \
  CONFIG.pf0_sriov_bar3_enabled                                {false} \
  CONFIG.pf0_sriov_bar3_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar3_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar3_size                                   {2} \
  CONFIG.pf0_sriov_bar3_type                                   {N/A} \
  CONFIG.pf0_sriov_bar4_64bit                                  {false} \
  CONFIG.pf0_sriov_bar4_enabled                                {false} \
  CONFIG.pf0_sriov_bar4_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar4_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar4_size                                   {2} \
  CONFIG.pf0_sriov_bar4_type                                   {N/A} \
  CONFIG.pf0_sriov_bar5_64bit                                  {false} \
  CONFIG.pf0_sriov_bar5_enabled                                {false} \
  CONFIG.pf0_sriov_bar5_prefetchable                           {false} \
  CONFIG.pf0_sriov_bar5_scale                                  {Kilobytes} \
  CONFIG.pf0_sriov_bar5_size                                   {2} \
  CONFIG.pf0_sriov_bar5_type                                   {N/A} \
  CONFIG.pf0_sriov_cap_ver                                     {1} \
  CONFIG.pf0_sub_class_interface_menu                          {16450_compatible_serial_controller} \
  CONFIG.pf0_sub_class_interface_menu_mqdma                    {Other_memory_controller} \
  CONFIG.pf0_subsystem_id                                      {0007} \
  CONFIG.pf0_subsystem_vendor_id                               {10EE} \
  CONFIG.pf0_vendor_id_mqdma                                   {10EE} \
  CONFIG.pf1_Use_Class_Code_Lookup_Assistant_mqdma             {false} \
  CONFIG.pf1_bar0_64bit                                        {false} \
  CONFIG.pf1_bar0_64bit_mqdma                                  {false} \
  CONFIG.pf1_bar0_enabled                                      {true} \
  CONFIG.pf1_bar0_enabled_mqdma                                {true} \
  CONFIG.pf1_bar0_index                                        {0} \
  CONFIG.pf1_bar0_prefetchable                                 {false} \
  CONFIG.pf1_bar0_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar0_scale                                        {Megabytes} \
  CONFIG.pf1_bar0_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar0_size                                         {32} \
  CONFIG.pf1_bar0_size_mqdma                                   {128} \
  CONFIG.pf1_bar0_type                                         {Memory} \
  CONFIG.pf1_bar0_type_mqdma                                   {DMA} \
  CONFIG.pf1_bar1_64bit                                        {false} \
  CONFIG.pf1_bar1_64bit_mqdma                                  {false} \
  CONFIG.pf1_bar1_enabled                                      {true} \
  CONFIG.pf1_bar1_enabled_mqdma                                {false} \
  CONFIG.pf1_bar1_index                                        {7} \
  CONFIG.pf1_bar1_prefetchable                                 {false} \
  CONFIG.pf1_bar1_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar1_scale                                        {Kilobytes} \
  CONFIG.pf1_bar1_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar1_size                                         {128} \
  CONFIG.pf1_bar1_size_mqdma                                   {128} \
  CONFIG.pf1_bar1_type                                         {Memory} \
  CONFIG.pf1_bar1_type_mqdma                                   {N/A} \
  CONFIG.pf1_bar2_64bit                                        {true} \
  CONFIG.pf1_bar2_64bit_mqdma                                  {false} \
  CONFIG.pf1_bar2_enabled                                      {true} \
  CONFIG.pf1_bar2_enabled_mqdma                                {false} \
  CONFIG.pf1_bar2_index                                        {7} \
  CONFIG.pf1_bar2_prefetchable                                 {false} \
  CONFIG.pf1_bar2_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar2_scale                                        {Kilobytes} \
  CONFIG.pf1_bar2_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar2_size                                         {128} \
  CONFIG.pf1_bar2_size_mqdma                                   {128} \
  CONFIG.pf1_bar2_type                                         {Memory} \
  CONFIG.pf1_bar2_type_mqdma                                   {N/A} \
  CONFIG.pf1_bar3_64bit                                        {false} \
  CONFIG.pf1_bar3_64bit_mqdma                                  {false} \
  CONFIG.pf1_bar3_enabled                                      {false} \
  CONFIG.pf1_bar3_enabled_mqdma                                {false} \
  CONFIG.pf1_bar3_index                                        {7} \
  CONFIG.pf1_bar3_prefetchable                                 {false} \
  CONFIG.pf1_bar3_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar3_scale                                        {Kilobytes} \
  CONFIG.pf1_bar3_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar3_size                                         {128} \
  CONFIG.pf1_bar3_size_mqdma                                   {128} \
  CONFIG.pf1_bar3_type                                         {Memory} \
  CONFIG.pf1_bar3_type_mqdma                                   {N/A} \
  CONFIG.pf1_bar4_64bit                                        {true} \
  CONFIG.pf1_bar4_64bit_mqdma                                  {false} \
  CONFIG.pf1_bar4_enabled                                      {true} \
  CONFIG.pf1_bar4_enabled_mqdma                                {false} \
  CONFIG.pf1_bar4_index                                        {7} \
  CONFIG.pf1_bar4_prefetchable                                 {false} \
  CONFIG.pf1_bar4_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar4_scale                                        {Kilobytes} \
  CONFIG.pf1_bar4_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar4_size                                         {128} \
  CONFIG.pf1_bar4_size_mqdma                                   {128} \
  CONFIG.pf1_bar4_type                                         {Memory} \
  CONFIG.pf1_bar4_type_mqdma                                   {N/A} \
  CONFIG.pf1_bar5_enabled                                      {false} \
  CONFIG.pf1_bar5_enabled_mqdma                                {false} \
  CONFIG.pf1_bar5_index                                        {7} \
  CONFIG.pf1_bar5_prefetchable                                 {false} \
  CONFIG.pf1_bar5_prefetchable_mqdma                           {false} \
  CONFIG.pf1_bar5_scale                                        {Kilobytes} \
  CONFIG.pf1_bar5_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf1_bar5_size                                         {128} \
  CONFIG.pf1_bar5_size_mqdma                                   {128} \
  CONFIG.pf1_bar5_type                                         {Memory} \
  CONFIG.pf1_bar5_type_mqdma                                   {N/A} \
  CONFIG.pf1_base_class_menu                                   {Simple_communication_controllers} \
  CONFIG.pf1_base_class_menu_mqdma                             {Memory_controller} \
  CONFIG.pf1_class_code                                        {070001} \
  CONFIG.pf1_class_code_base                                   {07} \
  CONFIG.pf1_class_code_base_mqdma                             {05} \
  CONFIG.pf1_class_code_interface                              {01} \
  CONFIG.pf1_class_code_interface_mqdma                        {00} \
  CONFIG.pf1_class_code_mqdma                                  {058000} \
  CONFIG.pf1_class_code_sub                                    {00} \
  CONFIG.pf1_class_code_sub_mqdma                              {80} \
  CONFIG.pf1_device_id                                         {1041} \
  CONFIG.pf1_expansion_rom_enabled                             {false} \
  CONFIG.pf1_expansion_rom_scale                               {Kilobytes} \
  CONFIG.pf1_expansion_rom_size                                {4} \
  CONFIG.pf1_expansion_rom_type                                {N/A} \
  CONFIG.pf1_msi_enabled                                       {false} \
  CONFIG.pf1_msix_cap_pba_bir                                  {BAR_0} \
  CONFIG.pf1_msix_cap_pba_offset                               {00000000} \
  CONFIG.pf1_msix_cap_table_bir                                {BAR_0} \
  CONFIG.pf1_msix_cap_table_offset                             {00000000} \
  CONFIG.pf1_msix_cap_table_size                               {000} \
  CONFIG.pf1_msix_enabled                                      {false} \
  CONFIG.pf1_msix_enabled_mqdma                                {false} \
  CONFIG.pf1_pciebar2axibar_0                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_1                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_2                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_3                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_4                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_5                                  {0x0000000000000000} \
  CONFIG.pf1_pciebar2axibar_6                                  {0x0000000000000000} \
  CONFIG.pf1_rbar_cap_bar0                                     {0x00000000fff0} \
  CONFIG.pf1_rbar_cap_bar1                                     {0x000000000000} \
  CONFIG.pf1_rbar_cap_bar2                                     {0x000000000000} \
  CONFIG.pf1_rbar_cap_bar3                                     {0x000000000000} \
  CONFIG.pf1_rbar_cap_bar4                                     {0x000000000000} \
  CONFIG.pf1_rbar_cap_bar5                                     {0x000000000000} \
  CONFIG.pf1_rbar_num                                          {1} \
  CONFIG.pf1_sriov_bar0_64bit                                  {false} \
  CONFIG.pf1_sriov_bar0_enabled                                {true} \
  CONFIG.pf1_sriov_bar0_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar0_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar0_size                                   {2} \
  CONFIG.pf1_sriov_bar0_type                                   {DMA} \
  CONFIG.pf1_sriov_bar1_64bit                                  {false} \
  CONFIG.pf1_sriov_bar1_enabled                                {false} \
  CONFIG.pf1_sriov_bar1_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar1_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar1_size                                   {2} \
  CONFIG.pf1_sriov_bar1_type                                   {N/A} \
  CONFIG.pf1_sriov_bar2_64bit                                  {false} \
  CONFIG.pf1_sriov_bar2_enabled                                {false} \
  CONFIG.pf1_sriov_bar2_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar2_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar2_size                                   {2} \
  CONFIG.pf1_sriov_bar2_type                                   {N/A} \
  CONFIG.pf1_sriov_bar3_64bit                                  {false} \
  CONFIG.pf1_sriov_bar3_enabled                                {false} \
  CONFIG.pf1_sriov_bar3_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar3_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar3_size                                   {2} \
  CONFIG.pf1_sriov_bar3_type                                   {N/A} \
  CONFIG.pf1_sriov_bar4_64bit                                  {false} \
  CONFIG.pf1_sriov_bar4_enabled                                {false} \
  CONFIG.pf1_sriov_bar4_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar4_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar4_size                                   {2} \
  CONFIG.pf1_sriov_bar4_type                                   {N/A} \
  CONFIG.pf1_sriov_bar5_64bit                                  {false} \
  CONFIG.pf1_sriov_bar5_enabled                                {false} \
  CONFIG.pf1_sriov_bar5_prefetchable                           {false} \
  CONFIG.pf1_sriov_bar5_scale                                  {Kilobytes} \
  CONFIG.pf1_sriov_bar5_size                                   {2} \
  CONFIG.pf1_sriov_bar5_type                                   {N/A} \
  CONFIG.pf1_sub_class_interface_menu                          {16450_compatible_serial_controller} \
  CONFIG.pf1_sub_class_interface_menu_mqdma                    {Other_memory_controller} \
  CONFIG.pf1_vendor_id                                         {10EE} \
  CONFIG.pf1_vendor_id_mqdma                                   {10EE} \
  CONFIG.pf2_Use_Class_Code_Lookup_Assistant_mqdma             {false} \
  CONFIG.pf2_bar0_64bit                                        {false} \
  CONFIG.pf2_bar0_64bit_mqdma                                  {false} \
  CONFIG.pf2_bar0_enabled                                      {true} \
  CONFIG.pf2_bar0_enabled_mqdma                                {true} \
  CONFIG.pf2_bar0_index                                        {0} \
  CONFIG.pf2_bar0_prefetchable                                 {false} \
  CONFIG.pf2_bar0_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar0_scale                                        {Kilobytes} \
  CONFIG.pf2_bar0_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar0_size                                         {128} \
  CONFIG.pf2_bar0_size_mqdma                                   {128} \
  CONFIG.pf2_bar0_type                                         {Memory} \
  CONFIG.pf2_bar0_type_mqdma                                   {DMA} \
  CONFIG.pf2_bar1_64bit                                        {false} \
  CONFIG.pf2_bar1_64bit_mqdma                                  {false} \
  CONFIG.pf2_bar1_enabled                                      {true} \
  CONFIG.pf2_bar1_enabled_mqdma                                {false} \
  CONFIG.pf2_bar1_index                                        {7} \
  CONFIG.pf2_bar1_prefetchable                                 {false} \
  CONFIG.pf2_bar1_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar1_scale                                        {Kilobytes} \
  CONFIG.pf2_bar1_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar1_size                                         {128} \
  CONFIG.pf2_bar1_size_mqdma                                   {128} \
  CONFIG.pf2_bar1_type                                         {Memory} \
  CONFIG.pf2_bar1_type_mqdma                                   {N/A} \
  CONFIG.pf2_bar2_64bit                                        {false} \
  CONFIG.pf2_bar2_64bit_mqdma                                  {false} \
  CONFIG.pf2_bar2_enabled                                      {true} \
  CONFIG.pf2_bar2_enabled_mqdma                                {false} \
  CONFIG.pf2_bar2_index                                        {7} \
  CONFIG.pf2_bar2_prefetchable                                 {false} \
  CONFIG.pf2_bar2_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar2_scale                                        {Kilobytes} \
  CONFIG.pf2_bar2_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar2_size                                         {128} \
  CONFIG.pf2_bar2_size_mqdma                                   {128} \
  CONFIG.pf2_bar2_type                                         {Memory} \
  CONFIG.pf2_bar2_type_mqdma                                   {N/A} \
  CONFIG.pf2_bar3_64bit                                        {false} \
  CONFIG.pf2_bar3_64bit_mqdma                                  {false} \
  CONFIG.pf2_bar3_enabled                                      {true} \
  CONFIG.pf2_bar3_enabled_mqdma                                {false} \
  CONFIG.pf2_bar3_index                                        {7} \
  CONFIG.pf2_bar3_prefetchable                                 {false} \
  CONFIG.pf2_bar3_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar3_scale                                        {Kilobytes} \
  CONFIG.pf2_bar3_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar3_size                                         {128} \
  CONFIG.pf2_bar3_size_mqdma                                   {128} \
  CONFIG.pf2_bar3_type                                         {Memory} \
  CONFIG.pf2_bar3_type_mqdma                                   {N/A} \
  CONFIG.pf2_bar4_64bit                                        {false} \
  CONFIG.pf2_bar4_64bit_mqdma                                  {false} \
  CONFIG.pf2_bar4_enabled                                      {true} \
  CONFIG.pf2_bar4_enabled_mqdma                                {false} \
  CONFIG.pf2_bar4_index                                        {7} \
  CONFIG.pf2_bar4_prefetchable                                 {false} \
  CONFIG.pf2_bar4_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar4_scale                                        {Kilobytes} \
  CONFIG.pf2_bar4_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar4_size                                         {128} \
  CONFIG.pf2_bar4_size_mqdma                                   {128} \
  CONFIG.pf2_bar4_type                                         {Memory} \
  CONFIG.pf2_bar4_type_mqdma                                   {N/A} \
  CONFIG.pf2_bar5_enabled                                      {true} \
  CONFIG.pf2_bar5_enabled_mqdma                                {false} \
  CONFIG.pf2_bar5_index                                        {7} \
  CONFIG.pf2_bar5_prefetchable                                 {false} \
  CONFIG.pf2_bar5_prefetchable_mqdma                           {false} \
  CONFIG.pf2_bar5_scale                                        {Kilobytes} \
  CONFIG.pf2_bar5_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf2_bar5_size                                         {128} \
  CONFIG.pf2_bar5_size_mqdma                                   {128} \
  CONFIG.pf2_bar5_type                                         {Memory} \
  CONFIG.pf2_bar5_type_mqdma                                   {N/A} \
  CONFIG.pf2_base_class_menu                                   {Memory_controller} \
  CONFIG.pf2_base_class_menu_mqdma                             {Memory_controller} \
  CONFIG.pf2_class_code                                        {058000} \
  CONFIG.pf2_class_code_base                                   {05} \
  CONFIG.pf2_class_code_base_mqdma                             {05} \
  CONFIG.pf2_class_code_interface                              {00} \
  CONFIG.pf2_class_code_interface_mqdma                        {00} \
  CONFIG.pf2_class_code_mqdma                                  {058000} \
  CONFIG.pf2_class_code_sub                                    {80} \
  CONFIG.pf2_class_code_sub_mqdma                              {80} \
  CONFIG.pf2_device_id                                         {903F} \
  CONFIG.pf2_expansion_rom_enabled                             {false} \
  CONFIG.pf2_expansion_rom_scale                               {Kilobytes} \
  CONFIG.pf2_expansion_rom_size                                {4} \
  CONFIG.pf2_expansion_rom_type                                {N/A} \
  CONFIG.pf2_msi_enabled                                       {false} \
  CONFIG.pf2_msix_enabled_mqdma                                {false} \
  CONFIG.pf2_pciebar2axibar_0                                  {0x0000000000000000} \
  CONFIG.pf2_pciebar2axibar_1                                  {0x0000000000000000} \
  CONFIG.pf2_pciebar2axibar_2                                  {0x0000000000000000} \
  CONFIG.pf2_pciebar2axibar_3                                  {0x0000000000000000} \
  CONFIG.pf2_pciebar2axibar_4                                  {0x0000000000000000} \
  CONFIG.pf2_pciebar2axibar_5                                  {0x0000000000000000} \
  CONFIG.pf2_rbar_cap_bar0                                     {0x00000000fff0} \
  CONFIG.pf2_rbar_cap_bar1                                     {0x000000000000} \
  CONFIG.pf2_rbar_cap_bar2                                     {0x000000000000} \
  CONFIG.pf2_rbar_cap_bar3                                     {0x000000000000} \
  CONFIG.pf2_rbar_cap_bar4                                     {0x000000000000} \
  CONFIG.pf2_rbar_cap_bar5                                     {0x000000000000} \
  CONFIG.pf2_rbar_num                                          {1} \
  CONFIG.pf2_sriov_bar0_64bit                                  {false} \
  CONFIG.pf2_sriov_bar0_enabled                                {true} \
  CONFIG.pf2_sriov_bar0_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar0_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar0_size                                   {2} \
  CONFIG.pf2_sriov_bar0_type                                   {DMA} \
  CONFIG.pf2_sriov_bar1_64bit                                  {false} \
  CONFIG.pf2_sriov_bar1_enabled                                {false} \
  CONFIG.pf2_sriov_bar1_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar1_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar1_size                                   {2} \
  CONFIG.pf2_sriov_bar1_type                                   {N/A} \
  CONFIG.pf2_sriov_bar2_64bit                                  {false} \
  CONFIG.pf2_sriov_bar2_enabled                                {false} \
  CONFIG.pf2_sriov_bar2_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar2_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar2_size                                   {2} \
  CONFIG.pf2_sriov_bar2_type                                   {N/A} \
  CONFIG.pf2_sriov_bar3_64bit                                  {false} \
  CONFIG.pf2_sriov_bar3_enabled                                {false} \
  CONFIG.pf2_sriov_bar3_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar3_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar3_size                                   {2} \
  CONFIG.pf2_sriov_bar3_type                                   {N/A} \
  CONFIG.pf2_sriov_bar4_64bit                                  {false} \
  CONFIG.pf2_sriov_bar4_enabled                                {false} \
  CONFIG.pf2_sriov_bar4_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar4_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar4_size                                   {2} \
  CONFIG.pf2_sriov_bar4_type                                   {N/A} \
  CONFIG.pf2_sriov_bar5_64bit                                  {false} \
  CONFIG.pf2_sriov_bar5_enabled                                {false} \
  CONFIG.pf2_sriov_bar5_prefetchable                           {false} \
  CONFIG.pf2_sriov_bar5_scale                                  {Kilobytes} \
  CONFIG.pf2_sriov_bar5_size                                   {2} \
  CONFIG.pf2_sriov_bar5_type                                   {N/A} \
  CONFIG.pf2_sub_class_interface_menu                          {Other_memory_controller} \
  CONFIG.pf2_sub_class_interface_menu_mqdma                    {Other_memory_controller} \
  CONFIG.pf2_vendor_id_mqdma                                   {10EE} \
  CONFIG.pf3_Use_Class_Code_Lookup_Assistant_mqdma             {false} \
  CONFIG.pf3_bar0_64bit                                        {false} \
  CONFIG.pf3_bar0_64bit_mqdma                                  {false} \
  CONFIG.pf3_bar0_enabled                                      {true} \
  CONFIG.pf3_bar0_enabled_mqdma                                {true} \
  CONFIG.pf3_bar0_index                                        {0} \
  CONFIG.pf3_bar0_prefetchable                                 {false} \
  CONFIG.pf3_bar0_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar0_scale                                        {Kilobytes} \
  CONFIG.pf3_bar0_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar0_size                                         {128} \
  CONFIG.pf3_bar0_size_mqdma                                   {128} \
  CONFIG.pf3_bar0_type                                         {Memory} \
  CONFIG.pf3_bar0_type_mqdma                                   {DMA} \
  CONFIG.pf3_bar1_64bit                                        {false} \
  CONFIG.pf3_bar1_64bit_mqdma                                  {false} \
  CONFIG.pf3_bar1_enabled                                      {true} \
  CONFIG.pf3_bar1_enabled_mqdma                                {false} \
  CONFIG.pf3_bar1_index                                        {7} \
  CONFIG.pf3_bar1_prefetchable                                 {false} \
  CONFIG.pf3_bar1_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar1_scale                                        {Kilobytes} \
  CONFIG.pf3_bar1_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar1_size                                         {128} \
  CONFIG.pf3_bar1_size_mqdma                                   {128} \
  CONFIG.pf3_bar1_type                                         {Memory} \
  CONFIG.pf3_bar1_type_mqdma                                   {N/A} \
  CONFIG.pf3_bar2_64bit                                        {false} \
  CONFIG.pf3_bar2_64bit_mqdma                                  {false} \
  CONFIG.pf3_bar2_enabled                                      {true} \
  CONFIG.pf3_bar2_enabled_mqdma                                {false} \
  CONFIG.pf3_bar2_index                                        {7} \
  CONFIG.pf3_bar2_prefetchable                                 {false} \
  CONFIG.pf3_bar2_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar2_scale                                        {Kilobytes} \
  CONFIG.pf3_bar2_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar2_size                                         {128} \
  CONFIG.pf3_bar2_size_mqdma                                   {128} \
  CONFIG.pf3_bar2_type                                         {Memory} \
  CONFIG.pf3_bar2_type_mqdma                                   {N/A} \
  CONFIG.pf3_bar3_64bit                                        {false} \
  CONFIG.pf3_bar3_64bit_mqdma                                  {false} \
  CONFIG.pf3_bar3_enabled                                      {true} \
  CONFIG.pf3_bar3_enabled_mqdma                                {false} \
  CONFIG.pf3_bar3_index                                        {7} \
  CONFIG.pf3_bar3_prefetchable                                 {false} \
  CONFIG.pf3_bar3_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar3_scale                                        {Kilobytes} \
  CONFIG.pf3_bar3_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar3_size                                         {128} \
  CONFIG.pf3_bar3_size_mqdma                                   {128} \
  CONFIG.pf3_bar3_type                                         {Memory} \
  CONFIG.pf3_bar3_type_mqdma                                   {N/A} \
  CONFIG.pf3_bar4_64bit                                        {false} \
  CONFIG.pf3_bar4_64bit_mqdma                                  {false} \
  CONFIG.pf3_bar4_enabled                                      {true} \
  CONFIG.pf3_bar4_enabled_mqdma                                {false} \
  CONFIG.pf3_bar4_index                                        {7} \
  CONFIG.pf3_bar4_prefetchable                                 {false} \
  CONFIG.pf3_bar4_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar4_scale                                        {Kilobytes} \
  CONFIG.pf3_bar4_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar4_size                                         {128} \
  CONFIG.pf3_bar4_size_mqdma                                   {128} \
  CONFIG.pf3_bar4_type                                         {Memory} \
  CONFIG.pf3_bar4_type_mqdma                                   {N/A} \
  CONFIG.pf3_bar5_enabled                                      {true} \
  CONFIG.pf3_bar5_enabled_mqdma                                {false} \
  CONFIG.pf3_bar5_index                                        {7} \
  CONFIG.pf3_bar5_prefetchable                                 {false} \
  CONFIG.pf3_bar5_prefetchable_mqdma                           {false} \
  CONFIG.pf3_bar5_scale                                        {Kilobytes} \
  CONFIG.pf3_bar5_scale_mqdma                                  {Kilobytes} \
  CONFIG.pf3_bar5_size                                         {128} \
  CONFIG.pf3_bar5_size_mqdma                                   {128} \
  CONFIG.pf3_bar5_type                                         {Memory} \
  CONFIG.pf3_bar5_type_mqdma                                   {N/A} \
  CONFIG.pf3_base_class_menu                                   {Memory_controller} \
  CONFIG.pf3_base_class_menu_mqdma                             {Memory_controller} \
  CONFIG.pf3_class_code                                        {058000} \
  CONFIG.pf3_class_code_base                                   {05} \
  CONFIG.pf3_class_code_base_mqdma                             {05} \
  CONFIG.pf3_class_code_interface                              {00} \
  CONFIG.pf3_class_code_interface_mqdma                        {00} \
  CONFIG.pf3_class_code_mqdma                                  {058000} \
  CONFIG.pf3_class_code_sub                                    {80} \
  CONFIG.pf3_class_code_sub_mqdma                              {80} \
  CONFIG.pf3_device_id                                         {1039} \
  CONFIG.pf3_expansion_rom_enabled                             {false} \
  CONFIG.pf3_expansion_rom_scale                               {Kilobytes} \
  CONFIG.pf3_expansion_rom_size                                {4} \
  CONFIG.pf3_expansion_rom_type                                {N/A} \
  CONFIG.pf3_msi_enabled                                       {false} \
  CONFIG.pf3_msix_enabled_mqdma                                {false} \
  CONFIG.pf3_pciebar2axibar_0                                  {0x0000000000000000} \
  CONFIG.pf3_pciebar2axibar_1                                  {0x0000000000000000} \
  CONFIG.pf3_pciebar2axibar_2                                  {0x0000000000000000} \
  CONFIG.pf3_pciebar2axibar_3                                  {0x0000000000000000} \
  CONFIG.pf3_pciebar2axibar_4                                  {0x0000000000000000} \
  CONFIG.pf3_pciebar2axibar_5                                  {0x0000000000000000} \
  CONFIG.pf3_rbar_cap_bar0                                     {0x00000000fff0} \
  CONFIG.pf3_rbar_cap_bar1                                     {0x000000000000} \
  CONFIG.pf3_rbar_cap_bar2                                     {0x000000000000} \
  CONFIG.pf3_rbar_cap_bar3                                     {0x000000000000} \
  CONFIG.pf3_rbar_cap_bar4                                     {0x000000000000} \
  CONFIG.pf3_rbar_cap_bar5                                     {0x000000000000} \
  CONFIG.pf3_rbar_num                                          {1} \
  CONFIG.pf3_sriov_bar0_64bit                                  {false} \
  CONFIG.pf3_sriov_bar0_enabled                                {true} \
  CONFIG.pf3_sriov_bar0_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar0_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar0_size                                   {2} \
  CONFIG.pf3_sriov_bar0_type                                   {DMA} \
  CONFIG.pf3_sriov_bar1_64bit                                  {false} \
  CONFIG.pf3_sriov_bar1_enabled                                {false} \
  CONFIG.pf3_sriov_bar1_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar1_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar1_size                                   {2} \
  CONFIG.pf3_sriov_bar1_type                                   {N/A} \
  CONFIG.pf3_sriov_bar2_64bit                                  {false} \
  CONFIG.pf3_sriov_bar2_enabled                                {false} \
  CONFIG.pf3_sriov_bar2_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar2_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar2_size                                   {2} \
  CONFIG.pf3_sriov_bar2_type                                   {N/A} \
  CONFIG.pf3_sriov_bar3_64bit                                  {false} \
  CONFIG.pf3_sriov_bar3_enabled                                {false} \
  CONFIG.pf3_sriov_bar3_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar3_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar3_size                                   {2} \
  CONFIG.pf3_sriov_bar3_type                                   {N/A} \
  CONFIG.pf3_sriov_bar4_64bit                                  {false} \
  CONFIG.pf3_sriov_bar4_enabled                                {false} \
  CONFIG.pf3_sriov_bar4_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar4_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar4_size                                   {2} \
  CONFIG.pf3_sriov_bar4_type                                   {N/A} \
  CONFIG.pf3_sriov_bar5_64bit                                  {false} \
  CONFIG.pf3_sriov_bar5_enabled                                {false} \
  CONFIG.pf3_sriov_bar5_prefetchable                           {false} \
  CONFIG.pf3_sriov_bar5_scale                                  {Kilobytes} \
  CONFIG.pf3_sriov_bar5_size                                   {2} \
  CONFIG.pf3_sriov_bar5_type                                   {N/A} \
  CONFIG.pf3_sub_class_interface_menu                          {Other_memory_controller} \
  CONFIG.pf3_sub_class_interface_menu_mqdma                    {Other_memory_controller} \
  CONFIG.pf3_vendor_id_mqdma                                   {10EE} \
  CONFIG.pf_swap                                               {false} \
  CONFIG.pipe_line_stage                                       {2} \
  CONFIG.pipe_sim                                              {true} \
  CONFIG.pl_link_cap_max_link_speed                            {8.0_GT/s} \
  CONFIG.pl_link_cap_max_link_width                            {X16} \
  CONFIG.plltype                                               {QPLL1} \
  CONFIG.post_synth_sim_en                                     {false} \
  CONFIG.prog_usr_irq_vec_map                                  {false} \
  CONFIG.rbar_enable                                           {false} \
  CONFIG.rcfg_nph_fix_en                                       {false} \
  CONFIG.ref_clk_freq                                          {100_MHz} \
  CONFIG.replace_uram_with_bram                                {false} \
  CONFIG.runbit_fix                                            {true} \
  CONFIG.rx_detect                                             {Default} \
  CONFIG.s_axi_id_width                                        {4} \
  CONFIG.select_quad                                           {GTY_Quad_227} \
  CONFIG.set_finite_credit                                     {false} \
  CONFIG.shell_bridge                                          {false} \
  CONFIG.silicon_rev                                           {Pre-Production} \
  CONFIG.sim_model                                             {NO} \
  CONFIG.slot_cap_reg                                          {00000040} \
  CONFIG.soft_reset_en                                         {false} \
  CONFIG.split_dma                                             {false} \
  CONFIG.split_dma_single_pf                                   {false} \
  CONFIG.sys_reset_polarity                                    {ACTIVE_LOW} \
  CONFIG.tandem_enable_rfsoc                                   {false} \
  CONFIG.timeout0_sel                                          {14} \
  CONFIG.timeout1_sel                                          {15} \
  CONFIG.timeout_mult                                          {3} \
  CONFIG.tl_credits_cd                                         {15} \
  CONFIG.tl_credits_ch                                         {15} \
  CONFIG.tl_pf_enable_reg                                      {1} \
  CONFIG.tl_tx_mux_strict_priority                             {false} \
  CONFIG.two_bypass_bar                                        {false} \
  CONFIG.type1_membase_memlimit_enable                         {Disabled} \
  CONFIG.type1_prefetchable_membase_memlimit                   {Disabled} \
  CONFIG.use_standard_interfaces                               {false} \
  CONFIG.user_pf_two_axilite_bar_en                            {false} \
  CONFIG.usplus_es1_seqnum_bypass                              {false} \
  CONFIG.usr_irq_exdes                                         {false} \
  CONFIG.usrint_expn                                           {false} \
  CONFIG.vcu118_board                                          {false} \
  CONFIG.vcu1525_ddr_ex                                        {false} \
  CONFIG.vdm_en                                                {false} \
  CONFIG.vendor_id                                             {10EE} \
  CONFIG.versal                                                {false} \
  CONFIG.virtio_exdes                                          {false} \
  CONFIG.virtio_perf_exdes                                     {false} \
  CONFIG.vu9p_board                                            {false} \
  CONFIG.vu9p_tul_ex                                           {false} \
  CONFIG.warm_reboot_sbr_fix                                   {false} \
  CONFIG.xdma_axi_intf_mm                                      {AXI_Memory_Mapped} \
  CONFIG.xdma_axilite_slave                                    {false} \
  CONFIG.xdma_dsc_bypass                                       {false} \
  CONFIG.xdma_en                                               {true} \
  CONFIG.xdma_non_incremental_exdes                            {false} \
  CONFIG.xdma_num_usr_irq                                      {1} \
  CONFIG.xdma_pcie_64bit_en                                    {false} \
  CONFIG.xdma_pcie_prefetchable                                {false} \
  CONFIG.xdma_rnum_chnl                                        {1} \
  CONFIG.xdma_rnum_rids                                        {32} \
  CONFIG.xdma_scale                                            {Kilobytes} \
  CONFIG.xdma_size                                             {64} \
  CONFIG.xdma_st_infinite_desc_exdes                           {false} \
  CONFIG.xdma_sts_ports                                        {false} \
  CONFIG.xdma_wnum_chnl                                        {1} \
  CONFIG.xdma_wnum_rids                                        {16} \
  CONFIG.xlnx_ref_board                                        {AU50} \
]

