// *************************************************************************
//
// Wrapper around the axil_host_switch IP — AXI-Lite host control
// distributor (1 slave, 4 masters).
//
// *************************************************************************
`timescale 1ns/1ps
module axil_host_switch_wrapper (
  input        aclk,
  input        aresetn,

  // Slave port
  axi_if.slave s00,

  // Master ports
  axi_if.master m00,
  axi_if.master m01,
  axi_if.master m02,
  axi_if.master m03,

  // Switch status
  output       aresetn_out,
  output       pc_asserted,
  output [1:0] pc_status
);

  // The IP's slave port s00 is AXI-Lite, so it only carries the
  // address/data/response phases — no id/len/size/burst/lock/cache/qos/
  // user/wlast/rlast.  Drive those outbound fields of the parent's
  // full-AXI4 interface to constants here so downstream consumers see
  // sane values; the inbound AXI4-only fields from the parent are just
  // ignored (the IP doesn't have ports for them).
  assign s00.bid   = '0;
  assign s00.rid   = '0;
  assign s00.rlast = 1'b1;

  axil_host_switch u_switch (
    .aclk              (aclk),
    .aresetn           (aresetn),
    .aresetn_out       (aresetn_out),
    .pc_asserted       (pc_asserted),
    .pc_status         (pc_status),

    // Slave port s00 (AXI-Lite)
    .s00_axi_awaddr    (s00.awaddr),
    .s00_axi_awprot    (s00.awprot),
    .s00_axi_awvalid   (s00.awvalid),
    .s00_axi_awready   (s00.awready),
    .s00_axi_wdata     (s00.wdata),
    .s00_axi_wstrb     (s00.wstrb),
    .s00_axi_wvalid    (s00.wvalid),
    .s00_axi_wready    (s00.wready),
    .s00_axi_bresp     (s00.bresp),
    .s00_axi_bvalid    (s00.bvalid),
    .s00_axi_bready    (s00.bready),
    .s00_axi_araddr    (s00.araddr),
    .s00_axi_arprot    (s00.arprot),
    .s00_axi_arvalid   (s00.arvalid),
    .s00_axi_arready   (s00.arready),
    .s00_axi_rdata     (s00.rdata),
    .s00_axi_rresp     (s00.rresp),
    .s00_axi_rvalid    (s00.rvalid),
    .s00_axi_rready    (s00.rready),

    // Master port m00
    .m00_axi_awid      (m00.awid),
    .m00_axi_awaddr    (m00.awaddr),
    .m00_axi_awlen     (m00.awlen),
    .m00_axi_awsize    (m00.awsize),
    .m00_axi_awburst   (m00.awburst),
    .m00_axi_awlock    (m00.awlock),
    .m00_axi_awcache   (m00.awcache),
    .m00_axi_awprot    (m00.awprot),
    .m00_axi_awqos     (m00.awqos),
    .m00_axi_awuser    (),
    .m00_axi_awvalid   (m00.awvalid),
    .m00_axi_awready   (m00.awready),
    .m00_axi_wdata     (m00.wdata),
    .m00_axi_wstrb     (m00.wstrb),
    .m00_axi_wlast     (m00.wlast),
    .m00_axi_wuser     (),
    .m00_axi_wvalid    (m00.wvalid),
    .m00_axi_wready    (m00.wready),
    .m00_axi_bid       (m00.bid),
    .m00_axi_bresp     (m00.bresp),
    .m00_axi_buser     (1'b0),
    .m00_axi_bvalid    (m00.bvalid),
    .m00_axi_bready    (m00.bready),
    .m00_axi_arid      (m00.arid),
    .m00_axi_araddr    (m00.araddr),
    .m00_axi_arlen     (m00.arlen),
    .m00_axi_arsize    (m00.arsize),
    .m00_axi_arburst   (m00.arburst),
    .m00_axi_arlock    (m00.arlock),
    .m00_axi_arcache   (m00.arcache),
    .m00_axi_arprot    (m00.arprot),
    .m00_axi_arqos     (m00.arqos),
    .m00_axi_aruser    (),
    .m00_axi_arvalid   (m00.arvalid),
    .m00_axi_arready   (m00.arready),
    .m00_axi_rid       (m00.rid),
    .m00_axi_rdata     (m00.rdata),
    .m00_axi_rresp     (m00.rresp),
    .m00_axi_rlast     (m00.rlast),
    .m00_axi_ruser     (1'b0),
    .m00_axi_rvalid    (m00.rvalid),
    .m00_axi_rready    (m00.rready),

    // Master port m01
    .m01_axi_awid      (m01.awid),
    .m01_axi_awaddr    (m01.awaddr),
    .m01_axi_awlen     (m01.awlen),
    .m01_axi_awsize    (m01.awsize),
    .m01_axi_awburst   (m01.awburst),
    .m01_axi_awlock    (m01.awlock),
    .m01_axi_awcache   (m01.awcache),
    .m01_axi_awprot    (m01.awprot),
    .m01_axi_awqos     (m01.awqos),
    .m01_axi_awuser    (),
    .m01_axi_awvalid   (m01.awvalid),
    .m01_axi_awready   (m01.awready),
    .m01_axi_wdata     (m01.wdata),
    .m01_axi_wstrb     (m01.wstrb),
    .m01_axi_wlast     (m01.wlast),
    .m01_axi_wuser     (),
    .m01_axi_wvalid    (m01.wvalid),
    .m01_axi_wready    (m01.wready),
    .m01_axi_bid       (m01.bid),
    .m01_axi_bresp     (m01.bresp),
    .m01_axi_buser     (1'b0),
    .m01_axi_bvalid    (m01.bvalid),
    .m01_axi_bready    (m01.bready),
    .m01_axi_arid      (m01.arid),
    .m01_axi_araddr    (m01.araddr),
    .m01_axi_arlen     (m01.arlen),
    .m01_axi_arsize    (m01.arsize),
    .m01_axi_arburst   (m01.arburst),
    .m01_axi_arlock    (m01.arlock),
    .m01_axi_arcache   (m01.arcache),
    .m01_axi_arprot    (m01.arprot),
    .m01_axi_arqos     (m01.arqos),
    .m01_axi_aruser    (),
    .m01_axi_arvalid   (m01.arvalid),
    .m01_axi_arready   (m01.arready),
    .m01_axi_rid       (m01.rid),
    .m01_axi_rdata     (m01.rdata),
    .m01_axi_rresp     (m01.rresp),
    .m01_axi_rlast     (m01.rlast),
    .m01_axi_ruser     (1'b0),
    .m01_axi_rvalid    (m01.rvalid),
    .m01_axi_rready    (m01.rready),

    // Master port m02
    .m02_axi_awid      (m02.awid),
    .m02_axi_awaddr    (m02.awaddr),
    .m02_axi_awlen     (m02.awlen),
    .m02_axi_awsize    (m02.awsize),
    .m02_axi_awburst   (m02.awburst),
    .m02_axi_awlock    (m02.awlock),
    .m02_axi_awcache   (m02.awcache),
    .m02_axi_awprot    (m02.awprot),
    .m02_axi_awqos     (m02.awqos),
    .m02_axi_awuser    (),
    .m02_axi_awvalid   (m02.awvalid),
    .m02_axi_awready   (m02.awready),
    .m02_axi_wdata     (m02.wdata),
    .m02_axi_wstrb     (m02.wstrb),
    .m02_axi_wlast     (m02.wlast),
    .m02_axi_wuser     (),
    .m02_axi_wvalid    (m02.wvalid),
    .m02_axi_wready    (m02.wready),
    .m02_axi_bid       (m02.bid),
    .m02_axi_bresp     (m02.bresp),
    .m02_axi_buser     (1'b0),
    .m02_axi_bvalid    (m02.bvalid),
    .m02_axi_bready    (m02.bready),
    .m02_axi_arid      (m02.arid),
    .m02_axi_araddr    (m02.araddr),
    .m02_axi_arlen     (m02.arlen),
    .m02_axi_arsize    (m02.arsize),
    .m02_axi_arburst   (m02.arburst),
    .m02_axi_arlock    (m02.arlock),
    .m02_axi_arcache   (m02.arcache),
    .m02_axi_arprot    (m02.arprot),
    .m02_axi_arqos     (m02.arqos),
    .m02_axi_aruser    (),
    .m02_axi_arvalid   (m02.arvalid),
    .m02_axi_arready   (m02.arready),
    .m02_axi_rid       (m02.rid),
    .m02_axi_rdata     (m02.rdata),
    .m02_axi_rresp     (m02.rresp),
    .m02_axi_rlast     (m02.rlast),
    .m02_axi_ruser     (1'b0),
    .m02_axi_rvalid    (m02.rvalid),
    .m02_axi_rready    (m02.rready),

    // Master port m03
    .m03_axi_awid      (m03.awid),
    .m03_axi_awaddr    (m03.awaddr),
    .m03_axi_awlen     (m03.awlen),
    .m03_axi_awsize    (m03.awsize),
    .m03_axi_awburst   (m03.awburst),
    .m03_axi_awlock    (m03.awlock),
    .m03_axi_awcache   (m03.awcache),
    .m03_axi_awprot    (m03.awprot),
    .m03_axi_awqos     (m03.awqos),
    .m03_axi_awuser    (),
    .m03_axi_awvalid   (m03.awvalid),
    .m03_axi_awready   (m03.awready),
    .m03_axi_wdata     (m03.wdata),
    .m03_axi_wstrb     (m03.wstrb),
    .m03_axi_wlast     (m03.wlast),
    .m03_axi_wuser     (),
    .m03_axi_wvalid    (m03.wvalid),
    .m03_axi_wready    (m03.wready),
    .m03_axi_bid       (m03.bid),
    .m03_axi_bresp     (m03.bresp),
    .m03_axi_buser     (1'b0),
    .m03_axi_bvalid    (m03.bvalid),
    .m03_axi_bready    (m03.bready),
    .m03_axi_arid      (m03.arid),
    .m03_axi_araddr    (m03.araddr),
    .m03_axi_arlen     (m03.arlen),
    .m03_axi_arsize    (m03.arsize),
    .m03_axi_arburst   (m03.arburst),
    .m03_axi_arlock    (m03.arlock),
    .m03_axi_arcache   (m03.arcache),
    .m03_axi_arprot    (m03.arprot),
    .m03_axi_arqos     (m03.arqos),
    .m03_axi_aruser    (),
    .m03_axi_arvalid   (m03.arvalid),
    .m03_axi_arready   (m03.arready),
    .m03_axi_rid       (m03.rid),
    .m03_axi_rdata     (m03.rdata),
    .m03_axi_rresp     (m03.rresp),
    .m03_axi_rlast     (m03.rlast),
    .m03_axi_ruser     (1'b0),
    .m03_axi_rvalid    (m03.rvalid),
    .m03_axi_rready    (m03.rready)
  );

endmodule: axil_host_switch_wrapper
